'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowRight, Check, CheckCircle2, Code2, Copy, Eye, EyeOff, GitFork, LockKeyhole, Octagon, ShieldCheck, Wallet } from 'lucide-react';
import { toast, Toaster } from 'sonner';
import { Brand, NetworkBadge } from '@/components/ringside/shell';
import { LandingReveals, CountUp, TypedCall, MaskedAmount } from '@/components/ringside/landing-motion';
import { ProofIcon } from '@/components/ringside/proof-icons';
import { Menu, X } from 'lucide-react';
const repo='https://github.com/mayorXBT/Ringside-MCP';
const groups={Wallet:[['wallet_info','Read wallet state and address','read'],['register_private_wallet','Create a private wallet','read'],['deposit','Move public funds into the shielded balance','spends funds'],['sync_balance','Update decrypted balance','read'],['read_history','Read private payment history','read']],Spend:[['private_transfer','Send a private payment','spends funds'],['withdraw','Move funds to a public wallet','spends funds'],['deposit_with_interface_setup','Fund with interface setup','spends funds'],['create_test_token','Create a devnet test asset','spends funds']],Seller:[['create_payment_request','Quote a payment','read'],['pay_payment_request','Pay a seller privately','spends funds'],['verify_payment','Verify a received payment','read']],Owner:[['get_policy','Read current owner rules','read']], 'Swap & escrow (Preview)':[...['swap_make_order','swap_take_order','swap_take_order_verifiable','swap_cancel_order','swap_list_orders','escrow_lock','escrow_release','escrow_withdraw','escrow_list'].map(s=>[s,'Discoverable; engine unavailable','Preview'])]} as const;
const snippets={
  'Claude Desktop config':`{
  "mcpServers": {
    "ringside": {
      "command": "node",
      "args": ["--use-env-proxy", "/absolute/path/Ringside-MCP/packages/mcp/dist/index.js"],
      "env": {
        "HELIUS_API_KEY": "your-devnet-key",
        "RINGSIDE_KEYPAIR": "/absolute/path/agent.json"
      }
    }
  }
}`,
  CLI:'pnpm install && pnpm build\nnode packages/mcp/dist/index.js init --owner <OWNER>\nnode packages/mcp/dist/index.js pair',
  'Seller API':'GET /report → 402 Payment Required\npay_payment_request → X-PAYMENT\nverify_payment → 200 OK'
};
const faqs=[['Is Ringside on mainnet?','No. Devnet beta. Mainnet RPC URLs are refused by the server.'],['What exactly is hidden?','Amount and asset of private transfers. Sender, recipient and signature are public. Deposits and withdrawals are fully public.'],['Can my agent change its own limits?','No. There is no policy-writing MCP tool. Changes require your owner wallet signature.'],['What happens when I press Stop spending?','Your wallet signs a kill-switch change. The agent’s next spend is rejected with KILL_SWITCH. Reads still work.'],['Where are the keys?','Self-hosted keys stay in a local file with mode 600. In hosted mode, Ringside stores an encrypted agent key server-side and decrypts it in memory to execute requests.'],['Do swap and escrow work?','Not yet in Ringside. The tools return ENGINE_UNAVAILABLE; upstream programs pass on localnet.'],['What is verified today?','The full private payment loop passes on Zolana localnet. Devnet registration and deposits pass; private transfer awaits Helius proof services.'],['Does the hosted dashboard work?','The self-hosted dashboard can pair with a local agent. Hosted login and wallet creation need production Postgres, which is not connected yet.']];
function Title({eyebrow,children}:{eyebrow:string;children:React.ReactNode}){return <div style={{maxWidth:730,marginBottom:36}}><div className="mono" style={{color:'var(--accent)',fontSize:12,marginBottom:12}}>{eyebrow}</div><h2 className="landing-h2">{children}</h2></div>}
export default function Home(){const [group,setGroup]=useState<keyof typeof groups>('Wallet'),[snippet,setSnippet]=useState<keyof typeof snippets>('Claude Desktop config'),[menu,setMenu]=useState(false);const copy=async(value:string)=>{await navigator.clipboard.writeText(value);toast.success('Copied to clipboard')};return <LandingReveals><Toaster theme="light"/>
<header className="zero-header">
  <div className="zero-announcement"><span>Building for Colosseum World’s Fair</span><ArrowRight size={15}/></div>
  <div className="zero-nav landing-container"><Brand/><nav className="zero-nav-links" aria-label="Main navigation"><a href="#how">How it works</a><a href="#use-cases">Use cases</a><a href="#tools">Tools</a><a href="#controls">Controls</a><a href="#privacy">Privacy</a><a href="#custody">Custody</a><a href="/docs">Docs</a><a href="#contact">Contact</a><Link href="/demo">Try the live demo</Link></nav><div className="zero-nav-actions"><a className="zero-nav-github" href={repo} target="_blank" rel="noreferrer">GitHub</a><Link className="zero-pill black" href="/app">Open dashboard <ArrowRight size={16}/></Link><button className="zero-mobile-menu" aria-label="Open navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={21}/>:<Menu size={21}/>}</button></div></div>
  {menu&&<nav className="zero-mobile-links" aria-label="Mobile navigation">{[['How it works','#how'],['Use cases','#use-cases'],['Tools','#tools'],['Controls','#controls'],['Privacy','#privacy'],['What’s private','#private-faq'],['Custody','#custody'],['Docs','/docs'],['Contact','#contact'],['Try the live demo','/demo'],['Open dashboard','/app']].map(([name,href])=><a onClick={()=>setMenu(false)} key={name} href={href}>{name}</a>)}</nav>}
</header>
<section className="zero-hero"><div className="landing-container"><h1>Private payments for agents.</h1><p className="zero-hero-sub">Controls for owners. Set limits, sign every policy change, and stop spending in one tap.</p><div className="zero-hero-demo"><Link className="zero-pill outline" href="/demo">Try the live demo <ArrowRight size={16}/></Link><span>No install · live devnet transfer and withdrawal with a browser burner</span></div><div className="zero-audience"><article className="zero-audience-card"><div className="zero-eyebrow">/ FOR AGENT BUILDERS</div><h2>Add private payments to your agent</h2><p>One MCP server for wallets, private transfers, and seller payments on Solana devnet.</p><a className="zero-pill black" href="/onboard">Start building <ArrowRight size={17}/></a></article><article className="zero-audience-card dark"><div className="zero-eyebrow">/ FOR OWNERS</div><h2>Control what your agent spends</h2><p>Set caps and allowlists with your wallet. See private balance and activity in one place.</p><Link className="zero-pill white" href="/app">Open dashboard <ArrowRight size={17}/></Link></article></div><div className="zero-stat-pill"><span><CountUp to={25}/> MCP tools</span><span><CountUp to={3}/> spend limits</span><span>Owner-signed kill switch</span><span>Solana devnet</span></div><p className="zero-honesty">Devnet beta. Private transfers hide amount and asset; sender, recipient, deposits, and withdrawals are public. Test funds only.</p></div></section>
<section className="zero-product" data-reveal id="product"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ THE OWNER VIEW</div><h2>See what your agent can spend.</h2><p>Private balance, live activity, limits, and an emergency stop in one place.</p></div><div className="zero-browser-frame"><div className="zero-browser-bar"><span className="zero-browser-mark">R</span><span>ringside-dashboard.vercel.app/app</span><span className="zero-browser-live">Dashboard preview</span></div><picture><source media="(max-width: 700px)" srcSet="/dashboard-preview-mobile.webp"/><img src="/dashboard-preview.webp" alt="Ringside owner dashboard showing private balance, spend limits, and activity with illustrative localnet data" width="1280" height="760" /></picture></div><p className="zero-image-note">Actual Ringside dashboard UI. Amounts shown are illustrative localnet fixture data; devnet private transfers remain blocked by upstream proof services.</p></div></section>
<section className="zero-section zero-proof" data-reveal id="proof"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ BUILT FOR REAL AGENTS</div><h2>Everything around the payment.</h2><p>Privacy is useful when the owner can still see, limit, and verify what an agent does.</p></div><div className="zero-bento"><article className="zero-tile zero-tile-wide"><span className="zero-icon-chip"><ProofIcon kind="private"/></span><div><h3>Amount + asset hidden</h3><p>Default private transfers hide both on-chain. Sender, recipient, and signature remain public.</p><div className="zero-explorer-mini"><span>WHAT THE EXPLORER SEES</span><div>Amount <MaskedAmount/> <b>·</b> Asset ••••</div><small>Sender + recipient visible</small></div></div></article><article className="zero-tile zero-tile-dark"><span className="zero-icon-chip"><ProofIcon kind="key"/></span><div><h3>Local keys in self-host mode.</h3><p>Self-hosted agent keys stay on the agent machine. Hosted keys are encrypted server-side.</p><div className="zero-key-mini"><span>agent.json</span><span>SELF-HOSTED</span></div></div></article><article className="zero-tile"><span className="zero-icon-chip"><ProofIcon kind="tools"/></span><div><strong className="zero-tile-number"><CountUp to={25}/></strong><h3>MCP tools</h3><div className="zero-tool-mini">wallet · spend · seller</div></div></article><article className="zero-tile"><span className="zero-icon-chip"><ProofIcon kind="policy"/></span><div><strong className="zero-tile-number"><CountUp to={60} suffix="s"/></strong><h3>Owner-signed changes</h3><div className="zero-policy-mini">Signature expires in 60 seconds</div></div></article><article className="zero-tile"><span className="zero-icon-chip"><ProofIcon kind="seller"/></span><div><strong className="zero-tile-number zero-tile-flow">402 → pay → verified</strong><h3>Seller flow</h3><div className="zero-seller-mini">Request → private pay → verified</div></div></article><article className="zero-tile zero-tile-wide zero-helius"><span className="zero-icon-chip"><ProofIcon kind="helius"/></span><div><h3>Built on Helius Privacy</h3><p>Solana Rings balances, Photon indexing and proving. Ringside adds the agent tools and owner controls.</p><div className="zero-built-logos"><img src="/helius-logo.svg" alt="Helius" width="140" height="30"/><img src="/solana-logo.svg" alt="Solana" width="112" height="45"/></div></div></article></div></div></section>
<section className="zero-section zero-how" data-reveal id="how"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ HOW IT WORKS</div><h2>From setup to spend.</h2><p>Ringside runs beside your agent. The owner stays in control of every rule.</p></div><div className="zero-steps">{[['01','Install','Run the MCP server next to Claude, Cursor, or another MCP client.'],['02','Fund','Deposit devnet SOL. Deposits are public on-chain.'],['03','Set limits','Choose per-payment, session, and daily caps with your wallet.'],['04','Pay','The agent sends a private transfer; you see the amount locally.']].map(([n,title,body])=><div className="zero-step" key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>
<section className="zero-section zero-use-cases" data-reveal id="use-cases"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ USE CASES</div><h2>Pay for work, not accounts.</h2><p>Give an agent a budget and let the seller verify a payment before returning the result.</p></div><div className="zero-use-grid"><article><div className="zero-use-icon"><Code2 size={25}/></div><span>01 / DATA</span><h3>Purchase a report</h3><p>An analyst agent pays for a market report when it needs one. The seller verifies the receipt before delivering the file.</p><div className="zero-use-mini"><b>GET /report</b><span>402 → verified → 200</span></div></article><article><div className="zero-use-icon"><Activity size={25}/></div><span>02 / APIS</span><h3>Call a paid endpoint</h3><p>A research agent can buy a single API response inside its owner limit, without a standing subscription or saved card.</p><div className="zero-use-mini"><b>Per request</b><span>Policy checked first</span></div></article><article className="dark"><div className="zero-use-icon"><ShieldCheck size={25}/></div><span>03 / AUTOMATION</span><h3>Delegate a narrow budget</h3><p>An operator gives a workflow a capped wallet and a kill switch. The agent can spend within the rule, then report its activity.</p><div className="zero-use-mini"><b>Owner controls</b><span>Agent cannot edit them</span></div></article></div><p className="zero-use-caveat">These are example workflows. The seller payment loop passed on Zolana localnet; live devnet private payment is pending Helius proof-service recovery.</p></div></section>
<section className="zero-section zero-tools" data-reveal id="tools"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ MCP SURFACE</div><h2>One server. Every money verb.</h2><p>The tools your agent can call, and the owner rules it cannot change.</p></div><div className="zero-tools-layout"><div className="zero-tool-list"><div className="zero-tool-tabs" role="tablist" aria-label="Tool groups">{Object.keys(groups).map(key=><button role="tab" aria-selected={group===key} key={key} className={group===key?'selected':''} onClick={()=>setGroup(key as keyof typeof groups)}>{key}</button>)}</div><div className="zero-tool-rows">{groups[group].map(([name,desc,type])=><div className="zero-tool-row" key={name}><div><strong>{name}</strong><p>{desc}</p></div><span>{type}</span></div>)}</div>{group==='Swap & escrow (Preview)'?<p className="zero-tool-caution">Preview tools return <code>ENGINE_UNAVAILABLE</code> in Ringside today. Upstream examples pass on localnet; do not lock funds.</p>:<p className="zero-tool-caution">Also available: create_private_wallet, get_private_balance, and get_private_history aliases.</p>}</div><div className="zero-tool-code"><div className="zero-code-heading"><Code2 size={22}/><span>AGENT CALL</span></div><TypedCall text={group==='Seller'?`create_payment_request({ amount: "0.003", asset: "SOL" })

→ 402 Payment Required
→ pay_payment_request
→ verify_payment: accepted`:group==='Swap & escrow (Preview)'?`swap_make_order(...)

→ ENGINE_UNAVAILABLE

No funds moved.`:group==='Owner'?`get_policy()

→ read-only policy snapshot

Only the owner wallet can sign changes.`:`private_transfer({
  to: "79AR…Er9J",
  amount: "0.003",
  asset: "SOL"
})

→ policy allowed
→ amount + asset hidden on-chain`} complete={group==='Swap & escrow (Preview)'?'Unavailable on this network':group==='Owner'?'✓ policy read':'✓ sent privately'}/><div className="zero-code-footer">Runs on the agent’s machine · transfer loop verified on localnet</div></div></div></div></section>
<section className="zero-section zero-controls" data-reveal id="controls"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ OWNER CONTROLS</div><h2>Rules run before your agent spends.</h2><p>Set the rules once. Every payment is checked before the agent can move funds.</p></div><div className="zero-controls-visual"><div className="zero-controls-main"><div className="zero-control-head"><span>Spending policy</span><span className="zero-policy-status"><Check size={15}/> Active</span></div><div className="zero-limit-feature"><div><div className="zero-limit-label">Today · rolling 24 hours</div><div className="zero-limit-value"><CountUp to={0.12} decimals={2}/> <span>/ 0.5 SOL</span></div></div><div className="zero-limit-track"><div/></div><div className="zero-limit-remaining">0.38 SOL remaining</div></div><div className="zero-rule-list"><div><span>Per payment</span><strong>0.05 SOL</strong></div><div><span>Per session</span><strong>0.2 SOL</strong></div><div><span>Recipients</span><strong>Allowlist off</strong></div></div></div><aside className="zero-controls-stop"><span className="zero-stop-icon"><Octagon size={27}/></span><h3>One signature stops every spend.</h3><p>Your wallet signs the change. The next payment fails with <code>KILL_SWITCH</code>. Balances and history stay readable.</p><Link className="zero-pill white" href="/app">See owner controls <ArrowRight size={17}/></Link></aside></div><p className="zero-controls-note">Agents can read their policy. They cannot change it. Owner signatures include a nonce and expire in 60 seconds.</p></div></section>
<section className="zero-section zero-seller" data-reveal id="seller"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ SELLER PAYMENTS</div><h2>Charge agents. Verify privately.</h2><p>A seller returns a payment request. The agent pays. The seller verifies before serving the result.</p></div><div className="zero-seller-visual"><div className="zero-seller-request"><div className="zero-flow-tag">01 / REQUEST</div><strong>402</strong><div className="zero-flow-mini">GET /report <span>Payment Required</span></div><span>Seller responds with <b>402 Payment Required</b>.</span></div><div className="zero-flow-arrow">→</div><div className="zero-seller-payment"><div className="zero-flow-tag">02 / PAY</div><strong>Private pay</strong><div className="zero-flow-mini">Amount <MaskedAmount/></div><span>Agent pays with the asset and amount in the request.</span></div><div className="zero-flow-arrow">→</div><div className="zero-seller-verify"><div className="zero-flow-tag">03 / VERIFY</div><strong>200 OK</strong><div className="zero-flow-mini">✓ Payment verified</div><span>The seller checks amount, asset, payer, expiry, and replay before serving data.</span></div></div><div className="zero-seller-foot"><span><CheckCircle2 size={20}/> Replay attempts are rejected</span><p>Verified end to end on Zolana localnet. No on-chain memo binds the nonce yet, so the verifier also rejects payments older than the request.</p></div></div></section>
<section className="zero-section zero-custody" data-reveal id="custody"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ KEY CUSTODY</div><h2>Choose who holds the agent key.</h2><p>Both modes use owner controls. The custody boundary is different, so choose the one that matches your risk model.</p></div><div className="zero-custody-grid"><article><span>01 / SELF-HOSTED</span><h3>Keep the key on your machine.</h3><p>The MCP server reads a local agent keypair. Ringside’s hosted dashboard can pair with its local control API, but the key file never travels to the dashboard.</p><ul><li>Agent key in a local file, mode 600</li><li>Owner-signed policy changes</li><li>You run and secure the MCP process</li></ul><Link href="/docs#self-host" className="zero-pill black">Self-host guide <ArrowRight size={16}/></Link></article><article className="dark"><span>02 / HOSTED CONNECTOR</span><h3>Ringside holds an encrypted agent key.</h3><p>Hosted mode creates the agent key server-side and stores it encrypted. Ringside decrypts it in memory to execute authorized requests. Fund only the capped agent wallet with devnet test SOL.</p><ul><li>Default 0.05 SOL per payment</li><li>Default 0.2 SOL per 24 hours</li><li>Production signup awaits Postgres</li></ul><Link href="/onboard" className="zero-pill white">Hosted setup status <ArrowRight size={16}/></Link></article></div><p className="zero-custody-foot">Neither mode makes deposits or withdrawals private. Hosted operation and real connector login remain unverified in production.</p></div></section>
<section className="zero-section zero-privacy" data-reveal id="privacy"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ PRIVACY MODEL</div><h2>Exactly what is private.</h2><p>Amounts and assets can be hidden. The rest of the chain does not disappear.</p></div><div className="zero-privacy-table"><div className="privacy-row privacy-head"><strong>Action</strong><strong><EyeOff size={18}/>Hidden on-chain</strong><strong><Eye size={18}/>Public on-chain</strong></div>{[['Private transfer (default ring)','Amount, asset','Sender, recipient, signature, timing'],['Deposit into private balance','—','Wallet, amount, asset'],['Withdraw to a public wallet','—','Recipient, amount, asset'],['Seller payment (402 flow)','Amount, asset','Payer, seller, signature'],['Policy and caps','Off-chain','Owner policy is local or stored encrypted in hosted mode']].map(([a,b,c])=><div className="privacy-row" key={a}><strong>{a}</strong><span>{b}</span><span>{c}</span></div>)}</div><div className="zero-privacy-notes"><div><LockKeyhole size={22}/><strong>Choose custody</strong><p>Self-hosted keys stay local; hosted keys are encrypted server-side. No tool returns the key.</p></div><div><ProofIcon kind="policy"/><strong>Localhost control</strong><p>Pairing token for reads. Owner signature for writes.</p></div><div><Wallet size={22}/><strong>Devnet only</strong><p>Mainnet RPC URLs are refused. Use test funds.</p></div></div><p className="zero-privacy-foot">Funding is public; payments are private. Deposit and withdrawal sizes and timing can still reveal patterns.</p></div></section>
<section className="zero-section zero-private-faq" data-reveal id="private-faq"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ WHAT’S PRIVATE</div><h2>Where the privacy boundary is.</h2><p>Helius’s default confidential Ring hides transfer fields. Entry and exit are public transactions.</p></div><div className="zero-private-faq-grid"><details open><summary>Is a deposit private?<span>+</span></summary><p>No. A deposit reveals the sending wallet, destination, asset, and amount. It creates an encrypted private balance afterward. Helius documents that a deposit needs no ZK proof.</p><a href="https://www.helius.dev/docs/privacy/guides/deposit" target="_blank" rel="noreferrer">Helius deposit guide ↗</a></details><details><summary>Is a withdrawal private?<span>+</span></summary><p>No. The recipient, asset, and amount are public when funds leave the private balance. A withdrawal uses a proof to spend encrypted state, but it does not conceal the public exit.</p><a href="https://www.helius.dev/docs/privacy/guides/withdraw" target="_blank" rel="noreferrer">Helius withdrawal guide ↗</a></details><details><summary>Does a private transfer hide everyone?<span>+</span></summary><p>Not in the default Ring. The amount and asset are encrypted; sender and recipient addresses, signature, and timing remain visible. Helius also describes custom anonymous Rings, but Ringside does not offer those here.</p><a href="https://www.helius.dev/docs/privacy/guides/transfer" target="_blank" rel="noreferrer">Helius transfer guide ↗</a></details><details><summary>Will Ringside fall back to a public payment?<span>+</span></summary><p>No automatic public payment is performed when a private transfer fails or a recipient is unregistered. The payment fails. A deliberate withdrawal is a separate, public action. The policy’s fallback setting is present but does not implement a silent public transfer.</p><Link href="/docs#guide-withdraw">Read the withdrawal guide ↗</Link></details></div></div></section>
<section className="zero-section zero-install" data-reveal id="install"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ GET STARTED</div><h2>From source to first payment.</h2><p>Install the MCP server, pair your agent, and set the rules from your owner wallet.</p></div><div className="zero-install-panel"><div className="zero-install-top"><div><span className="zero-eyebrow">/ DEVELOPER SETUP</span><h3>Start building in minutes.</h3><p>Runs locally with Claude Desktop, Claude Code, Cursor, and other MCP clients.</p></div><a className="zero-pill white" href={repo} target="_blank" rel="noreferrer">View repository <ArrowRight size={17}/></a></div><div className="zero-install-tabs">{Object.keys(snippets).map(key=><button className={snippet===key?'selected':''} key={key} onClick={()=>setSnippet(key as keyof typeof snippets)}>{key}</button>)}</div><div className="zero-install-code"><pre>{snippets[snippet]}</pre><button onClick={()=>void copy(snippets[snippet])} aria-label="Copy setup code"><Copy size={16}/> Copy</button></div><p>Built from source today. <code>npx ringside-mcp</code> is not published yet.</p></div></div></section>
<section className="zero-section zero-faq" data-reveal><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ QUESTIONS</div><h2>Know the limits before you connect.</h2></div><div className="zero-faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>
<section className="zero-section zero-contact" data-reveal id="contact"><div className="landing-container"><div className="zero-contact-panel"><div><span className="zero-eyebrow">/ WORK WITH RINGSIDE</span><h2>Building an agent that needs to pay?</h2><p>Tell us the workflow, asset, and client you use. We’ll help you map the right MCP tools and be direct about what is still devnet-only.</p><div className="zero-contact-actions"><a className="zero-pill white" href={`${repo}/issues/new`} target="_blank" rel="noreferrer">Contact us on GitHub <ArrowRight size={17}/></a><Link className="zero-pill outline" href="/docs">Read the docs <ArrowRight size={17}/></Link></div></div><aside><strong>Start with a question</strong><span>“Can my agent pay a seller after a 402 response?”</span><span>“Which transaction fields stay public?”</span><span>“How should I cap a self-hosted wallet?”</span></aside></div></div></section>
<section className="zero-final" data-reveal><div className="landing-container"><h2>Put a limit between your agent and your wallet.</h2><p>Private payments on Solana devnet, with owner controls that run before spend.</p><div><Link className="zero-pill black" href="/app">Open dashboard <ArrowRight size={17}/></Link><a className="zero-pill outline" href={repo} target="_blank" rel="noreferrer">View on GitHub</a></div></div></section><footer className="zero-footer"><div className="landing-container"><div className="zero-footer-grid"><div><Brand/><p>Private agent payments on Solana.</p></div><div><strong>Product</strong><a href="/app">Dashboard</a><a href="/app/audit">Auditor view</a><a href="#tools">Tools</a></div><div><strong>Developers</strong><a href={repo}>GitHub</a><a href="/brand">Brand kit</a><a href={`${repo}#readme`}>README</a><a href={`${repo}/blob/main/scripts/demo.md`}>Demo runbook</a></div></div><div className="zero-footer-legal">Ringside is experimental software on Solana devnet. Not a bank, custodian, or wallet provider. Use test funds only. MIT licensed.</div></div></footer></LandingReveals>}
