'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowRight, Check, CheckCircle2, Code2, Copy, Eye, EyeOff, GitFork, LockKeyhole, Octagon, ShieldCheck, Wallet } from 'lucide-react';
import { toast, Toaster } from 'sonner';
import { Brand, NetworkBadge } from '@/components/ringside/shell';
import { LandingReveals } from '@/components/ringside/landing-motion';
const repo='https://github.com/mayorXBT/Ringside-MCP';
const groups={Wallet:[['wallet_info','Read wallet state and address','read'],['register_private_wallet','Create a private wallet','read'],['deposit','Move public funds into the shielded balance','spends funds'],['sync_balance','Update decrypted balance','read'],['read_history','Read private payment history','read']],Spend:[['private_transfer','Send a private payment','spends funds'],['withdraw','Move funds to a public wallet','spends funds'],['deposit_with_interface_setup','Fund with interface setup','spends funds'],['create_test_token','Create a devnet test asset','spends funds']],Seller:[['create_payment_request','Quote a payment','read'],['pay_payment_request','Pay a seller privately','spends funds'],['verify_payment','Verify a received payment','read']],Owner:[['get_policy','Read current owner rules','read']], 'Swap & escrow (Preview)':[...['swap_make_order','swap_take_order','swap_take_order_verifiable','swap_cancel_order','swap_list_orders','escrow_lock','escrow_release','escrow_withdraw','escrow_list'].map(s=>[s,'Discoverable; engine unavailable','Preview'])]} as const;
const snippets={
  'Claude Desktop config':`{
  "mcpServers": {
    "ringside": {
      "command": "node",
      "args": ["--use-env-proxy", "/absolute/path/Ringside-MCP/packages/mcp/dist/index.js"],
      "env": {
        "HELIUS_API_KEY": "your-devnet-key",
        "RINGSIDE_KEYPAIR": "/absolute/path/agent.json"
      }
    }
  }
}`,
  CLI:'pnpm install && pnpm build\nnode packages/mcp/dist/index.js init --owner <OWNER>\nnode packages/mcp/dist/index.js pair',
  'Seller API':'GET /report → 402 Payment Required\npay_payment_request → X-PAYMENT\nverify_payment → 200 OK'
};
const faqs=[['Is Ringside on mainnet?','No. Devnet beta. Mainnet RPC URLs are refused by the server.'],['What exactly is hidden?','Amount and asset of private transfers. Sender, recipient and signature are public. Deposits and withdrawals are fully public.'],['Can my agent change its own limits?','No. There is no policy-writing MCP tool. Changes require your owner wallet signature.'],['What happens when I press Stop spending?','Your wallet signs a kill-switch change. The agent’s next spend is rejected with KILL_SWITCH. Reads still work.'],['Where are the keys?','On the agent’s machine, in ~/.ringside with mode 600. The dashboard never receives them.'],['Do swap and escrow work?','Not yet in Ringside. The tools return ENGINE_UNAVAILABLE; upstream programs pass on localnet.'],['What is verified today?','The full private payment loop passes on Zolana localnet. Devnet registration and deposits pass; private transfer awaits Helius proof services.'],['Does the hosted dashboard work?','Yes in Chrome, with its origin added to RINGSIDE_DASHBOARD_ORIGINS. It talks to your local agent at 127.0.0.1:7420.']];
function Title({eyebrow,children}:{eyebrow:string;children:React.ReactNode}){return <div style={{maxWidth:730,marginBottom:36}}><div className="mono" style={{color:'var(--accent)',fontSize:12,marginBottom:12}}>{eyebrow}</div><h2 className="landing-h2">{children}</h2></div>}
export default function Home(){const [group,setGroup]=useState<keyof typeof groups>('Wallet'),[snippet,setSnippet]=useState<keyof typeof snippets>('Claude Desktop config'),[menu,setMenu]=useState(false);const copy=async(value:string)=>{await navigator.clipboard.writeText(value);toast.success('Copied to clipboard')};return <LandingReveals><Toaster theme="light"/>
<header className="zero-header">
  <div className="zero-announcement"><span>Building for Colosseum World’s Fair</span><ArrowRight size={15}/></div>
  <div className="zero-nav landing-container"><Brand/><nav className="zero-nav-links" aria-label="Main navigation"><a href="#how">How it works</a><a href="#tools">Tools</a><a href="#controls">Controls</a><a href="#privacy">Privacy</a><a href={`${repo}#readme`}>Docs</a></nav><div className="zero-nav-actions"><a className="zero-nav-github" href={repo} target="_blank" rel="noreferrer">GitHub</a><Link className="zero-pill black" href="/app">Open dashboard <ArrowRight size={16}/></Link><button className="zero-mobile-menu" aria-label="Open navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button></div></div>
  {menu&&<nav className="zero-mobile-links" aria-label="Mobile navigation">{[['How it works','#how'],['Tools','#tools'],['Controls','#controls'],['Privacy','#privacy'],['Docs',`${repo}#readme`],['Open dashboard','/app']].map(([name,href])=><a onClick={()=>setMenu(false)} key={name} href={href}>{name}</a>)}</nav>}
</header>
<section className="zero-hero"><div className="landing-container"><h1>Private payments for agents</h1><p className="zero-hero-sub">Give any MCP agent a private way to pay. Set its limits, sign every policy change, and stop spending in one tap.</p><div className="zero-audience"><article className="zero-audience-card"><div className="zero-eyebrow">/ FOR AGENT BUILDERS</div><h2>Add private payments to your agent</h2><p>One MCP server for wallets, private transfers, and seller payments on Solana devnet.</p><a className="zero-pill black" href="#install">Start building <ArrowRight size={17}/></a></article><article className="zero-audience-card dark"><div className="zero-eyebrow">/ FOR OWNERS</div><h2>Control what your agent spends</h2><p>Set caps and allowlists with your wallet. See private balance and activity in one place.</p><Link className="zero-pill white" href="/app">Open dashboard <ArrowRight size={17}/></Link></article></div><div className="zero-stat-pill"><span>25 MCP tools</span><span>3 spend limits</span><span>Owner-signed kill switch</span><span>Solana devnet</span></div><p className="zero-honesty">Devnet beta. Private transfers hide amount and asset; sender, recipient, deposits, and withdrawals are public. Test funds only.</p></div></section>
<section className="zero-product" data-reveal id="product"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ THE OWNER VIEW</div><h2>See what your agent can spend.</h2><p>Private balance, live activity, limits, and an emergency stop in one place.</p></div><div className="zero-browser-frame"><div className="zero-browser-bar"><span className="zero-browser-mark">R</span><span>ringside-dashboard.vercel.app/app</span><span className="zero-browser-live">Dashboard preview</span></div><picture><source media="(max-width: 700px)" srcSet="/dashboard-preview-mobile.png"/><img src="/dashboard-preview.png" alt="Ringside owner dashboard showing private balance, spend limits, and activity with illustrative localnet data" width="1280" height="760" /></picture></div><p className="zero-image-note">Actual Ringside dashboard UI. Amounts shown are illustrative localnet fixture data; devnet private transfers remain blocked by upstream proof services.</p></div></section>
<section className="zero-section zero-proof" data-reveal id="proof"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ BUILT FOR REAL AGENTS</div><h2>Everything around the payment.</h2><p>Privacy is useful when the owner can still see, limit, and verify what an agent does.</p></div><div className="zero-bento"><article className="zero-tile zero-tile-wide"><span className="zero-icon-chip"><EyeOff size={23}/></span><div><h3>Amount + asset hidden</h3><p>Default private transfers hide both on-chain. Sender, recipient, and signature remain public.</p></div></article><article className="zero-tile zero-tile-dark"><span className="zero-icon-chip"><LockKeyhole size={23}/></span><div><h3>Keys stay local.</h3><p>The agent keypair never leaves its machine.</p></div></article><article className="zero-tile"><span className="zero-icon-chip"><Code2 size={22}/></span><div><strong className="zero-tile-number">25</strong><h3>MCP tools</h3></div></article><article className="zero-tile"><span className="zero-icon-chip"><ShieldCheck size={22}/></span><div><strong className="zero-tile-number">60s</strong><h3>Owner-signed changes</h3></div></article><article className="zero-tile"><span className="zero-icon-chip"><CheckCircle2 size={22}/></span><div><strong className="zero-tile-number zero-tile-flow">402 → pay → verified</strong><h3>Seller flow</h3></div></article><article className="zero-tile zero-tile-wide zero-helius"><span className="zero-icon-chip"><Activity size={22}/></span><div><h3>Built on Helius Privacy</h3><p>Solana Rings balances, Photon indexing and proving. Ringside adds the agent tools and owner controls.</p></div></article></div></div></section>
<section className="zero-section zero-how" data-reveal id="how"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ HOW IT WORKS</div><h2>From setup to spend.</h2><p>Ringside runs beside your agent. The owner stays in control of every rule.</p></div><div className="zero-steps">{[['01','Install','Run the MCP server next to Claude, Cursor, or another MCP client.'],['02','Fund','Deposit devnet SOL. Deposits are public on-chain.'],['03','Set limits','Choose per-payment, session, and daily caps with your wallet.'],['04','Pay','The agent sends a private transfer; you see the amount locally.']].map(([n,title,body])=><div className="zero-step" key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>
<section className="zero-section zero-tools" data-reveal id="tools"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ MCP SURFACE</div><h2>One server. Every money verb.</h2><p>The tools your agent can call, and the owner rules it cannot change.</p></div><div className="zero-tools-layout"><div className="zero-tool-list"><div className="zero-tool-tabs" role="tablist" aria-label="Tool groups">{Object.keys(groups).map(key=><button role="tab" aria-selected={group===key} key={key} className={group===key?'selected':''} onClick={()=>setGroup(key as keyof typeof groups)}>{key}</button>)}</div><div className="zero-tool-rows">{groups[group].map(([name,desc,type])=><div className="zero-tool-row" key={name}><div><strong>{name}</strong><p>{desc}</p></div><span>{type}</span></div>)}</div>{group==='Swap & escrow (Preview)'?<p className="zero-tool-caution">Preview tools return <code>ENGINE_UNAVAILABLE</code> in Ringside today. Upstream examples pass on localnet; do not lock funds.</p>:<p className="zero-tool-caution">Also available: create_private_wallet, get_private_balance, and get_private_history aliases.</p>}</div><div className="zero-tool-code"><div className="zero-code-heading"><Code2 size={22}/><span>AGENT CALL</span></div><pre>{group==='Seller'?`create_payment_request({ amount: "0.003", asset: "SOL" })

→ 402 Payment Required
→ pay_payment_request
→ verify_payment: accepted`:group==='Swap & escrow (Preview)'?`swap_make_order(...)

→ ENGINE_UNAVAILABLE

No funds moved.`:group==='Owner'?`get_policy()

→ read-only policy snapshot

Only the owner wallet can sign changes.`:`private_transfer({
  to: "79AR…Er9J",
  amount: "0.003",
  asset: "SOL"
})

→ policy allowed
→ amount + asset hidden on-chain`}</pre><div className="zero-code-footer">Runs on the agent’s machine · transfer loop verified on localnet</div></div></div></div></section>
<section className="zero-section zero-controls" data-reveal id="controls"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ OWNER CONTROLS</div><h2>Rules run before your agent spends.</h2><p>Set the rules once. Every payment is checked before the agent can move funds.</p></div><div className="zero-controls-visual"><div className="zero-controls-main"><div className="zero-control-head"><span>Spending policy</span><span className="zero-policy-status"><Check size={15}/> Active</span></div><div className="zero-limit-feature"><div><div className="zero-limit-label">Today · rolling 24 hours</div><div className="zero-limit-value">0.12 <span>/ 0.5 SOL</span></div></div><div className="zero-limit-track"><div/></div><div className="zero-limit-remaining">0.38 SOL remaining</div></div><div className="zero-rule-list"><div><span>Per payment</span><strong>0.05 SOL</strong></div><div><span>Per session</span><strong>0.2 SOL</strong></div><div><span>Recipients</span><strong>Allowlist off</strong></div></div></div><aside className="zero-controls-stop"><span className="zero-stop-icon"><Octagon size={27}/></span><h3>One signature stops every spend.</h3><p>Your wallet signs the change. The next payment fails with <code>KILL_SWITCH</code>. Balances and history stay readable.</p><Link className="zero-pill white" href="/app">See owner controls <ArrowRight size={17}/></Link></aside></div><p className="zero-controls-note">Agents can read their policy. They cannot change it. Owner signatures include a nonce and expire in 60 seconds.</p></div></section>
<section className="zero-section zero-seller" data-reveal id="seller"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ SELLER PAYMENTS</div><h2>Charge agents. Verify privately.</h2><p>A seller returns a payment request. The agent pays. The seller verifies before serving the result.</p></div><div className="zero-seller-visual"><div className="zero-seller-request"><div className="zero-flow-tag">01 / REQUEST</div><strong>GET /report</strong><span>Seller responds with <b>402 Payment Required</b>.</span></div><div className="zero-flow-arrow">→</div><div className="zero-seller-payment"><div className="zero-flow-tag">02 / PAY</div><strong>private_transfer</strong><span>Agent pays with the asset and amount in the request.</span></div><div className="zero-flow-arrow">→</div><div className="zero-seller-verify"><div className="zero-flow-tag">03 / VERIFY</div><strong>200 OK</strong><span>The seller checks amount, asset, payer, expiry, and replay before serving data.</span></div></div><div className="zero-seller-foot"><span><CheckCircle2 size={20}/> Replay attempts are rejected</span><p>Verified end to end on Zolana localnet. No on-chain memo binds the nonce yet, so the verifier also rejects payments older than the request.</p></div></div></section>
<section className="zero-section zero-privacy" data-reveal id="privacy"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ PRIVACY MODEL</div><h2>Exactly what is private.</h2><p>Amounts and assets can be hidden. The rest of the chain does not disappear.</p></div><div className="zero-privacy-table"><div className="privacy-row privacy-head"><strong>Action</strong><strong><EyeOff size={18}/>Hidden on-chain</strong><strong><Eye size={18}/>Public on-chain</strong></div>{[['Private transfer (default ring)','Amount, asset','Sender, recipient, signature, timing'],['Deposit into private balance','—','Wallet, amount, asset'],['Withdraw to a public wallet','—','Recipient, amount, asset'],['Seller payment (402 flow)','Amount, asset','Payer, seller, signature'],['Policy and caps','Stays on agent machine','—']].map(([a,b,c])=><div className="privacy-row" key={a}><strong>{a}</strong><span>{b}</span><span>{c}</span></div>)}</div><div className="zero-privacy-notes"><div><LockKeyhole size={22}/><strong>Keys stay local</strong><p>The agent keypair is stored with mode 600. No tool or API returns it.</p></div><div><ShieldCheck size={22}/><strong>Localhost control</strong><p>Pairing token for reads. Owner signature for writes.</p></div><div><Wallet size={22}/><strong>Devnet only</strong><p>Mainnet RPC URLs are refused. Use test funds.</p></div></div><p className="zero-privacy-foot">Funding is public; payments are private. Deposit and withdrawal sizes and timing can still reveal patterns.</p></div></section>
<section className="zero-section zero-install" data-reveal id="install"><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ GET STARTED</div><h2>From source to first payment.</h2><p>Install the MCP server, pair your agent, and set the rules from your owner wallet.</p></div><div className="zero-install-panel"><div className="zero-install-top"><div><span className="zero-eyebrow">/ DEVELOPER SETUP</span><h3>Start building in minutes.</h3><p>Runs locally with Claude Desktop, Claude Code, Cursor, and other MCP clients.</p></div><a className="zero-pill white" href={repo} target="_blank" rel="noreferrer">View repository <ArrowRight size={17}/></a></div><div className="zero-install-tabs">{Object.keys(snippets).map(key=><button className={snippet===key?'selected':''} key={key} onClick={()=>setSnippet(key as keyof typeof snippets)}>{key}</button>)}</div><div className="zero-install-code"><pre>{snippets[snippet]}</pre><button onClick={()=>void copy(snippets[snippet])} aria-label="Copy setup code"><Copy size={16}/> Copy</button></div><p>Built from source today. <code>npx ringside-mcp</code> is not published yet.</p></div></div></section>
<section className="zero-section zero-faq" data-reveal><div className="landing-container"><div className="zero-section-heading"><div className="zero-eyebrow">/ QUESTIONS</div><h2>Know the limits before you connect.</h2></div><div className="zero-faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>
<section className="zero-final" data-reveal><div className="landing-container"><h2>Put a limit between your agent and your wallet.</h2><p>Private payments on Solana devnet, with owner controls that run before spend.</p><div><Link className="zero-pill black" href="/app">Open dashboard <ArrowRight size={17}/></Link><a className="zero-pill outline" href={repo} target="_blank" rel="noreferrer">View on GitHub</a></div></div></section><footer className="zero-footer"><div className="landing-container"><div className="zero-footer-grid"><div><Brand/><p>Private agent payments on Solana.</p></div><div><strong>Product</strong><a href="/app">Dashboard</a><a href="/app/audit">Auditor view</a><a href="#tools">Tools</a></div><div><strong>Developers</strong><a href={repo}>GitHub</a><a href={`${repo}#readme`}>README</a><a href={`${repo}/blob/main/scripts/demo.md`}>Demo runbook</a></div></div><div className="zero-footer-legal">Ringside is experimental software on Solana devnet. Not a bank, custodian, or wallet provider. Use test funds only. MIT licensed.</div></div></footer></LandingReveals>}
