// Run with PLAYWRIGHT_MODULE pointing at a Playwright installation if needed.
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const sharp = require(process.env.SHARP_MODULE || '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root = path.resolve(__dirname, '..');
const brand = __dirname;
const app = path.join(root, 'apps/dashboard/app');
const markLight = fs.readFileSync(path.join(brand, 'mark-light.svg'), 'utf8');
const markDark = fs.readFileSync(path.join(brand, 'mark-dark.svg'), 'utf8');
const regular = fs.readFileSync(path.join(brand, 'fonts/Geist-Regular.woff2')).toString('base64');
const bold = fs.readFileSync(path.join(brand, 'fonts/Geist-Bold.woff2')).toString('base64');
const font = `<style>@font-face{font-family:Geist;src:url(data:font/woff2;base64,${regular});font-weight:400}@font-face{font-family:Geist;src:url(data:font/woff2;base64,${bold});font-weight:700}*{box-sizing:border-box}body{margin:0;font-family:Geist,Arial,sans-serif}</style>`;
const lockup=(dark=false)=>`<div class="lockup">${dark?markDark:markLight}<strong>Ringside</strong></div>`;
const visual=`<div class="balance"><div class="cardtop"><span>PRIVATE BALANCE</span><span class="chip">DEMO DATA</span></div><strong>0.04 <small>SOL</small></strong><div class="meter"><i></i></div><p>Spend limit: 0.05 SOL / payment</p></div><div class="explorer"><span>PUBLIC EXPLORER</span><div><small>Amount</small><b>••••</b></div><div><small>Asset</small><b>••••</b></div><p>Sender + recipient visible</p></div>`;
const shared=`.lockup{display:flex;align-items:center;gap:15px;font-size:29px;letter-spacing:-.055em}.lockup svg{width:49px;height:49px}.tag{display:inline-block;padding:9px 15px;border-radius:100px;background:#e6e9ff;color:#43529a;font-size:15px;font-weight:700}.balance{position:absolute;background:#fff;border:1px solid #e4e7ef;border-radius:26px;box-shadow:0 30px 70px #1a244226;padding:28px;color:#0b0b0f}.cardtop{display:flex;align-items:center;justify-content:space-between;font-size:12px;font-weight:700;color:#747b8b;letter-spacing:.08em}.chip{background:#e7ebff;color:#5562a9;padding:8px 10px;border-radius:100px;font-size:10px;letter-spacing:0}.balance>strong{display:block;font-size:70px;letter-spacing:-.075em;margin:39px 0 17px;line-height:1}.balance small{font-size:25px;color:#7a8190;letter-spacing:0}.balance p{color:#737b8c;font-size:14px;margin:14px 0 0}.meter{height:10px;background:#e8ebf2;border-radius:20px;overflow:hidden}.meter i{display:block;width:42%;height:100%;background:#8b9bff;border-radius:20px}.explorer{position:absolute;background:#151519;color:#fff;border-radius:23px;padding:26px 29px;box-shadow:0 30px 70px #11121730}.explorer>span{display:block;color:#bfc7ff;font-size:11px;font-weight:700;letter-spacing:.09em;margin-bottom:25px}.explorer>div{display:flex;justify-content:space-between;gap:65px;border-top:1px solid #42444e;padding:13px 0}.explorer small{font-size:14px;color:#9da3b2}.explorer b{font-size:17px;letter-spacing:.1em}.explorer p{font-size:12px;color:#a9aebb;margin:10px 0 0}`;
const cards=[
 {out:path.join(app,'opengraph-image.png'),width:1200,height:630,html:`<div id="canvas" class="og">${lockup()}<div class="copy"><span class="tag">SOLANA DEVNET · MCP</span><h1>Private payments<br>for agents.<br><em>Controls for owners.</em></h1><p>Solana devnet · 25 MCP tools · Owner-signed limits</p></div>${visual}<div class="foot">ringside-dashboard.vercel.app</div></div><style>.og{width:1200px;height:630px;position:relative;overflow:hidden;background:#f4f5f8;color:#0b0b0f;padding:36px 50px}.og .copy{position:absolute;top:152px;left:50px;z-index:2}.og h1{font-size:56px;line-height:1.06;letter-spacing:-.06em;margin:23px 0 15px}.og h1 em{font-style:normal;color:#6879db}.og .copy p{font-size:16px;color:#646a78}.og .balance{width:440px;height:300px;left:714px;top:139px}.og .explorer{width:345px;left:628px;top:361px}.og .explorer>span{margin-bottom:10px}.og .explorer>div{padding:7px 0}.og .explorer p{margin:5px 0 0}.og .foot{position:absolute;left:50px;bottom:30px;font-size:14px;color:#737a88}</style>`},
 {out:path.join(brand,'intro-1920x1080.png'),width:1920,height:1080,html:`<div id="canvas" class="intro">${lockup()}<div class="copy"><span class="tag">COLOSSEUM WORLD'S FAIR · DEVNET BETA</span><h1>Private payments<br>for agents.</h1><h2>Controls for owners.</h2><p>Solana devnet · 25 MCP tools · Owner-signed limits</p></div>${visual}<div class="foot">RINGSIDE MCP <span>01 / INTRO</span></div></div><style>.intro{width:1920px;height:1080px;position:relative;overflow:hidden;background:#f4f5f8;padding:64px 88px;color:#0b0b0f}.intro .lockup{font-size:42px}.intro .lockup svg{width:70px;height:70px}.intro .copy{position:absolute;top:284px;left:88px;z-index:2}.intro h1{font-size:116px;line-height:1.02;letter-spacing:-.065em;margin:32px 0 0}.intro h2{font-size:72px;line-height:1;letter-spacing:-.055em;color:#6879db;margin:15px 0}.intro .copy p{font-size:24px;color:#646a78;margin-top:46px}.intro .balance{left:1180px;top:290px;width:610px;height:390px;padding:36px}.intro .balance>strong{font-size:96px;margin-top:62px}.intro .explorer{left:1030px;top:640px;width:500px}.intro .foot{position:absolute;bottom:57px;left:88px;right:88px;display:flex;justify-content:space-between;color:#777e8b;letter-spacing:.08em;font-size:16px}</style>`},
 {out:path.join(brand,'outro-1920x1080.png'),width:1920,height:1080,html:`<div id="canvas" class="outro">${lockup(true)}<span class="eyebrow">PRIVATE AGENT PAYMENTS · SOLANA DEVNET</span><h1>Private payments<br>for agents.</h1><h2>Controls for owners.</h2><p>One MCP interface · Owner-signed limits · Seller verification</p><div class="cta">Try the guided demo <span>↗</span></div><div class="url">ringside-dashboard.vercel.app/demo</div><div class="outro-mark">${markDark}</div></div><style>.outro{width:1920px;height:1080px;position:relative;overflow:hidden;background:#0b0b0f;color:#fff;padding:70px 90px}.outro .lockup{font-size:42px}.outro .lockup svg{width:70px;height:70px}.outro .eyebrow{position:absolute;top:300px;left:90px;color:#bac4ff;font-size:18px;font-weight:700;letter-spacing:.13em}.outro h1{position:absolute;top:338px;left:90px;font-size:120px;line-height:1.03;letter-spacing:-.065em;margin:0}.outro h2{position:absolute;top:598px;left:90px;font-size:76px;letter-spacing:-.06em;color:#aebaff;margin:0}.outro p{position:absolute;left:90px;top:718px;color:#c4c7d3;font-size:25px}.outro .cta{position:absolute;left:90px;bottom:115px;background:#fff;color:#0b0b0f;border-radius:100px;padding:23px 31px;font-size:23px;font-weight:700}.outro .cta span{margin-left:35px}.outro .url{position:absolute;left:90px;bottom:55px;color:#a7aab8;font-size:20px}.outro-mark{position:absolute;right:-130px;top:145px;width:850px;height:850px;opacity:.18}.outro-mark svg{width:100%;height:100%}</style>`}
];
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});
 for(const card of cards){const page=await browser.newPage({viewport:{width:card.width,height:card.height},deviceScaleFactor:1});await page.setContent(`<html><head>${font}<style>${shared}</style></head><body>${card.html}</body></html>`);await page.evaluate(()=>document.fonts.ready);await page.locator('#canvas').screenshot({path:card.out});await page.close();console.log(card.out)}
 await browser.close();
 const icon=fs.readFileSync(path.join(app,'icon.svg'));
 await sharp(icon).resize(180,180).png().toFile(path.join(app,'apple-icon.png'));
 for(const size of [16,32,48,64])await sharp(icon).resize(size,size).png().toFile(`/tmp/ringside-favicon-${size}.png`);
})();
