'use client';
import { useEffect, useState } from 'react';
import { useConnection, useWallet } from '@solana/wallet-adapter-react';
import Link from 'next/link';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Check, Copy, EyeOff, ExternalLink, LockKeyhole, RotateCcw, ShieldCheck, Wallet } from 'lucide-react';
import { Brand } from '@/components/ringside/shell';
const amount = 0.01;
const steps = ['Set a limit', 'Agent requests payment', 'Policy check', 'Private transfer', 'Seller verifies', 'Dashboard updates', 'Explorer view'];
const activity = { type: 'Private payment', recipient: 'Data seller · 8kQ…3sV', amount: '−0.01 SOL', status: 'Verified' };
export default function DemoClient() {
  const wallet=useWallet(), {connection}=useConnection();
  const [publicBalance,setPublicBalance]=useState<number|null>(null),[walletError,setWalletError]=useState('');
  const [burner,setBurner]=useState<{owner:string;balance:number|null;privateBalance:number|null;registerSignature:string|null;depositSignature:string|null;withdrawSignature:string|null}|null>(null);
  const [burnerBusy,setBurnerBusy]=useState(false),[burnerError,setBurnerError]=useState('');
  const [burnerCap,setBurnerCap]=useState('0.05'),[policyRejection,setPolicyRejection]=useState('');
  const [proofHealth,setProofHealth]=useState<{transferReady:boolean;reason:string|null;checkedAt:string}|null>(null),[proofChecking,setProofChecking]=useState(false);
  const [step,setStep]=useState(0),[limit,setLimit]=useState('0.05'),[checking,setChecking]=useState(false),[blocked,setBlocked]=useState(false);
  const reduced=useReducedMotion();
  useEffect(()=>{if(!wallet.publicKey){setPublicBalance(null);return}let active=true;const read=async()=>{try{const result=await connection.getBalance(wallet.publicKey!,'confirmed');if(active)setPublicBalance(result/1e9)}catch{if(active)setWalletError('Could not read devnet balance. Try again shortly.')}};void read();const timer=window.setInterval(()=>void read(),15000);return()=>{active=false;window.clearInterval(timer)}},[wallet.publicKey,connection]);
  useEffect(()=>{if(!localStorage.getItem('ringside:demo:burner-seed')&&!sessionStorage.getItem('ringside:demo:burner-seed'))return;void import('./burner').then(api=>api.burnerContext()).then(({owner})=>{let saved:Partial<NonNullable<typeof burner>>={};try{saved=JSON.parse(localStorage.getItem('ringside:demo:signatures')||'{}')}catch{}setBurner({owner,balance:null,privateBalance:null,registerSignature:saved.registerSignature||null,depositSignature:saved.depositSignature||null,withdrawSignature:saved.withdrawSignature||null})}).catch(()=>setBurnerError('Saved browser burner could not be restored.'))},[]);
  useEffect(()=>{if(!burner)return;localStorage.setItem('ringside:demo:signatures',JSON.stringify({registerSignature:burner.registerSignature,depositSignature:burner.depositSignature,withdrawSignature:burner.withdrawSignature}))},[burner]);
  useEffect(()=>{const saved=localStorage.getItem('ringside:demo:per-tx-cap');if(saved)setBurnerCap(saved)},[]);
  const saveBurnerCap=(value:string)=>{setBurnerCap(value);localStorage.setItem('ringside:demo:per-tx-cap',value);setPolicyRejection('')};
  const checkBrowserCap=(amountSol:number)=>{const cap=Number(burnerCap);if(!Number.isFinite(cap)||cap<=0||amountSol>cap){const message=`POLICY_DENIED: ${amountSol} SOL exceeds the browser burner’s ${burnerCap||'unset'} SOL transaction cap. No transaction was built or submitted.`;setPolicyRejection(message);return false}setPolicyRejection('');return true};
  const connect=async()=>{setWalletError('');try{if(!wallet.wallet){const phantom=wallet.wallets.find(item=>item.adapter.name==='Phantom');if(!phantom){setWalletError('Install Phantom, then switch it to Solana devnet.');return}wallet.select(phantom.adapter.name);return}await wallet.connect()}catch(error){setWalletError(error instanceof Error?error.message:'Could not connect Phantom')}};
  const checkProof=async()=>{setProofChecking(true);try{const response=await fetch('/api/demo/health',{cache:'no-store'});setProofHealth(await response.json())}catch{setProofHealth({transferReady:false,reason:'Could not check the devnet prover.',checkedAt:new Date().toISOString()})}finally{setProofChecking(false)}};
  const burnerAction=async(action:'create'|'register'|'deposit'|'sync'|'withdraw')=>{if(action==='deposit'&&!checkBrowserCap(0.01))return;setBurnerBusy(true);setBurnerError('');try{const api=await import('./burner');if(action==='create'){const {owner}=await api.burnerContext();setBurner({owner,balance:null,privateBalance:null,registerSignature:null,depositSignature:null,withdrawSignature:null});return}if(!burner)throw new Error('Create a browser burner first.');if(action==='register'){const result=await api.burnerRegister();setBurner(current=>current&&({...current,registerSignature:result.signature||'already registered'}))}if(action==='deposit'){const result=await api.burnerDeposit();setBurner(current=>current&&({...current,depositSignature:result.signature}))}if(action==='sync'){const result=await api.burnerBalance();setBurner(current=>current&&({...current,privateBalance:Number(result.lamports)/1e9}))}if(action==='withdraw'){const result=await api.burnerWithdraw(burner.owner);setBurner(current=>current&&({...current,withdrawSignature:result.signature}))}const {owner}=await api.burnerContext();const response=await fetch('https://api.devnet.solana.com',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'getBalance',params:[owner]})});const data=await response.json() as {result?:{value:number}};setBurner(current=>current&&({...current,balance:data.result?data.result.value/1e9:current.balance}))}catch(error){const causes:string[]=[];let current:unknown=error;for(let i=0;i<3&&current instanceof Error;i++){causes.push(current.message);current=current.cause}setBurnerError(causes.join(' → ')||'Devnet action failed')}finally{setBurnerBusy(false)}};
  useEffect(()=>{void checkProof()},[]);
  const limitNumber=Number(limit); const valid=Number.isFinite(limitNumber)&&limitNumber>0;
  useEffect(()=>{if(step!==2||blocked)return;const timer=window.setTimeout(()=>{setChecking(false);setBlocked(!valid||limitNumber<amount)},reduced?0:1100);setChecking(true);return()=>window.clearTimeout(timer)},[step,valid,limitNumber,reduced,blocked]);
  const next=()=>{if(step===2&&(blocked||checking))return;setStep(current=>Math.min(current+1,6))};
  const reset=()=>{setStep(0);setBlocked(false);setChecking(false)};
  return <div className="demo-page"><header className="demo-header"><Brand/><nav><Link href="/">Home</Link><Link href="/docs">Docs</Link><Link className="demo-header-cta" href="/app">Open dashboard <ArrowRight size={15}/></Link></nav></header>
  <main className="demo-main"><div className="demo-hero"><Link href="/" className="demo-back"><ArrowLeft size={15}/> Back to Ringside</Link><span className="demo-eyebrow">/ DEVNET TEST DRIVE · PHANTOM</span><h1>Test private payments on devnet.</h1><p>Connect Phantom to inspect your devnet balance. The guided payment sequence below remains recorded data while browser signing and Helius proof services are being verified.</p><div className="demo-wallet-panel"><div><span className="demo-eyebrow">/ YOUR WALLET · SOLANA DEVNET</span><h2>{wallet.publicKey?'Phantom connected':'Connect Phantom (Devnet)'}</h2><p>{wallet.publicKey?'Your public devnet balance is read directly from Solana RPC. Ringside does not receive your key.':'Switch Phantom to devnet, then connect. Connecting does not authorize a transaction.'}</p></div>{wallet.publicKey?<div className="demo-wallet-balance"><strong>{publicBalance===null?'Checking…':`${publicBalance.toFixed(4)} SOL`}</strong><code>{wallet.publicKey.toBase58().slice(0,6)}…{wallet.publicKey.toBase58().slice(-6)}</code><button type="button" onClick={()=>void wallet.disconnect()}>Disconnect</button></div>:<button className="demo-button primary" onClick={()=>void connect()}><Wallet size={17}/> Connect Phantom (Devnet)</button>}{wallet.publicKey&&publicBalance===0&&<div className="demo-faucet"><p>Your devnet balance is 0 SOL. Copy your address, then request test SOL from the Solana faucet.</p><button onClick={()=>void navigator.clipboard.writeText(wallet.publicKey!.toBase58())}><Copy size={15}/> Copy address</button><a href="https://faucet.solana.com/" target="_blank" rel="noreferrer">Open Solana faucet <ExternalLink size={15}/></a></div>}{walletError&&<p className="demo-wallet-error" role="alert">{walletError}</p>}</div><div className="demo-data-banner"><span>DEMO DATA</span><p>The payment sequence below is recorded; no transaction is submitted from this page yet. Helius’s devnet prover rejected our latest private transfer attempt.</p></div></div>
  <div className="demo-main" style={{paddingTop:0}}><div className="demo-wallet-panel"><div><span className="demo-eyebrow">/ LIVE DEVNET · BROWSER BURNER</span><h2>Run registration and deposit live</h2><p>Create a devnet-only key in your browser, then fund it from the faucet. The key stays in this browser’s local storage so you can return after closing the tab. A withdrawal still depends on Helius’s prover; do not deposit funds you need to recover promptly.</p></div>{!burner?<button className="demo-button primary" disabled={burnerBusy} onClick={()=>void burnerAction('create')}>Create browser burner</button>:<div style={{width:'100%',display:'grid',gap:12}}><code style={{overflowWrap:'anywhere'}}>{burner.owner}</code><p>Public: {burner.balance===null?'Refresh to check':`${burner.balance.toFixed(4)} SOL`} · Private: {burner.privateBalance===null?'Sync to check':`${burner.privateBalance.toFixed(4)} SOL`}</p><div style={{display:'flex',flexWrap:'wrap',gap:8}}><button className="demo-button secondary" onClick={()=>void navigator.clipboard.writeText(burner.owner)}>Copy address</button><a className="demo-button secondary" href="https://faucet.solana.com/" target="_blank" rel="noreferrer">Open faucet</a><button className="demo-button secondary" disabled={burnerBusy} onClick={()=>void burnerAction('register')}>Register wallet</button><button className="demo-button secondary" disabled={burnerBusy} onClick={()=>void burnerAction('deposit')}>Deposit 0.01 SOL</button><button className="demo-button secondary" disabled={burnerBusy} onClick={()=>void burnerAction('sync')}>Sync private balance</button><button className="demo-button secondary" disabled={burnerBusy} onClick={()=>void burnerAction('withdraw')}>Try withdrawal to public burner</button></div>{burnerBusy&&<p role="status">Waiting for devnet confirmation…</p>}{burnerError&&<p role="alert" className="demo-wallet-error">{burnerError}</p>}{(['registerSignature','depositSignature','withdrawSignature'] as const).map(key=>burner[key]&&<p key={key}>{key.replace('Signature','')}: {burner[key]==='already registered'?'Already registered':<a href={`https://explorer.solana.com/tx/${burner[key]}?cluster=devnet`} target="_blank" rel="noreferrer">{burner[key]} ↗</a>}</p>)}</div>}</div></div>
  {burner&&<div className="demo-wallet-panel" style={{marginBottom:32}}><div><span className="demo-eyebrow">/ LIVE BROWSER POLICY</span><h2>Test a real cap rejection</h2><p>This cap guards the browser burner’s deposit action before transaction building. It is stored in this browser only; it is separate from a Ringside MCP agent’s owner-signed policy.</p></div><label className="demo-input-label" htmlFor="burner-cap">Maximum per transaction · SOL</label><div className="demo-limit-input"><input id="burner-cap" type="number" min="0.001" step="0.001" value={burnerCap} onChange={event=>saveBurnerCap(event.target.value)}/><strong>SOL</strong></div><button className="demo-button secondary" type="button" onClick={()=>{if(checkBrowserCap(0.1))setPolicyRejection('The browser cap permits 0.1 SOL. This test does not submit a payment.')}}>Try 0.1 SOL payment</button>{policyRejection&&<p role="alert" className="demo-wallet-error">{policyRejection}</p>}</div>}
  {burner&&(burner.registerSignature||burner.depositSignature||burner.withdrawSignature)&&<div className="demo-explorer" style={{marginBottom:36}}><div><EyeOff size={18}/> WHAT THE EXPLORER SEES · REAL DEVNET TRANSACTIONS</div><dl>{burner.registerSignature&&burner.registerSignature!=='already registered'&&<><dt>Registration</dt><dd><a href={`https://explorer.solana.com/tx/${burner.registerSignature}?cluster=devnet`} target="_blank" rel="noreferrer">{burner.registerSignature.slice(0,12)}… ↗</a></dd><dt>Registered owner</dt><dd>{burner.owner.slice(0,8)}…</dd></>}{burner.depositSignature&&<><dt>Public deposit</dt><dd><a href={`https://explorer.solana.com/tx/${burner.depositSignature}?cluster=devnet`} target="_blank" rel="noreferrer">{burner.depositSignature.slice(0,12)}… ↗</a></dd><dt>Amount + asset</dt><dd>0.01 SOL · public</dd></>}{burner.withdrawSignature&&<><dt>Public withdrawal</dt><dd><a href={`https://explorer.solana.com/tx/${burner.withdrawSignature}?cluster=devnet`} target="_blank" rel="noreferrer">{burner.withdrawSignature.slice(0,12)}… ↗</a></dd><dt>Amount + asset</dt><dd>Visible on explorer</dd></>}</dl><p>Only private transfers mask amount and asset. Deposits and withdrawals reveal both.</p></div>}
  <div className="demo-workspace"><aside className="demo-steps" aria-label="Demo steps">{steps.map((label,index)=><button type="button" key={label} className={index===step?'active':index<step?'done':''} onClick={()=>{if(index<=step){setStep(index);setBlocked(false)}}} disabled={index>step}><span>{index<step?<Check size={14}/>:String(index+1).padStart(2,'0')}</span>{label}</button>)}<div className="demo-steps-foot">Recorded scenario · Solana devnet target</div></aside>
  <section className="demo-stage" aria-live="polite"><div className="demo-stage-top"><span>STEP {String(step+1).padStart(2,'0')} / 07</span><span className="demo-data-tag">DEMO DATA</span></div><AnimatePresence mode="wait"><motion.div key={step} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={reduced?undefined:{opacity:0,y:-8}} transition={{duration:reduced?0:0.35}}>
  {step===0&&<><span className="demo-eyebrow">/ OWNER CONTROL</span><h2>First, give the agent a limit.</h2><p className="demo-stage-copy">The owner sets a maximum payment. In Ringside, a real policy change requires the owner wallet’s signature. Here you can adjust the example limit freely.</p><label className="demo-input-label" htmlFor="demo-limit">Maximum per payment · SOL</label><div className="demo-limit-input"><input id="demo-limit" type="number" inputMode="decimal" min="0.001" step="0.001" value={limit} onChange={event=>setLimit(event.target.value)}/><strong>SOL</strong></div><div className="demo-policy-card"><ShieldCheck size={20}/><div><strong>Owner policy preview</strong><span>Agent cannot change this rule. Payments above the limit are blocked before a transaction is built.</span></div></div></>}
  {step===1&&<><span className="demo-eyebrow">/ AGENT REQUEST</span><h2>The agent finds a paid answer.</h2><p className="demo-stage-copy">A seller asks for 0.01 SOL before serving its data. The agent receives a payment request with a destination, amount, asset, resource, nonce, and expiry.</p><div className="demo-quote"><span>HTTP 402 · PAYMENT REQUIRED</span><strong>Market report</strong><div><span>Requested payment</span><b>0.01 SOL</b></div><div><span>Seller</span><b>8kQ…3sV</b></div><div><span>Expires</span><b>In 5 minutes</b></div></div></>}
  {step===2&&<><span className="demo-eyebrow">/ POLICY ENGINE</span><h2>{checking?'Checking the owner’s rule…':blocked?'Payment stopped by policy.':'Payment fits the limit.'}</h2><p className="demo-stage-copy">Ringside checks the kill switch, allowed asset and recipient, and transaction, session, and day caps before spending.</p><div className="demo-check-list"><div className={checking?'working':'passed'}><span>{checking?'…':<Check size={17}/>}</span>Kill switch is off</div><div className={checking?'working':blocked?'failed':'passed'}><span>{checking?'…':blocked?'×':<Check size={17}/>}</span>0.01 SOL ≤ {valid?limit:'—'} SOL per-payment limit</div><div className={checking?'working':blocked?'idle':'passed'}><span>{checking?'…':blocked?'—':<Check size={17}/>}</span>Recipient is registered and permitted</div></div>{blocked&&<div className="demo-blocked">A 0.01 SOL payment exceeds this example limit. Go back, raise it to at least 0.01 SOL, and try again.</div>}</>}
  {step===3&&<><span className="demo-eyebrow">/ PRIVATE TRANSFER</span><h2>Recorded private payment</h2><p className="demo-stage-copy">In the recorded localnet run, Ringside synced encrypted notes, requested a proof, and submitted a private transfer. The default Ring hides the amount and asset on-chain; sender and recipient remain visible.</p><div className="demo-policy-card"><ShieldCheck size={20}/><div><strong>{proofChecking?'Checking Helius devnet prover…':proofHealth?.transferReady?'Required prover key is available':'Helius prover unavailable, showing recorded run'}</strong><span>{proofHealth?.reason||'A key check alone cannot confirm that a full devnet transfer will succeed.'}</span></div><button type="button" onClick={()=>void checkProof()} disabled={proofChecking}>Retry</button></div><div className="demo-transfer"><div className="demo-transfer-node"><span>BUYER AGENT</span><strong>0.05 SOL</strong><small>Example private balance before</small></div><div className="demo-transfer-line"><LockKeyhole size={20}/><span>Encrypted amount + asset</span></div><div className="demo-transfer-node"><span>SELLER</span><strong>0.01 SOL</strong><small>Example payment received</small></div></div><p className="demo-stage-footnote">Illustrative values from a recorded scenario; this page does not submit a transaction.</p></>}
  {step===4&&<><span className="demo-eyebrow">/ SELLER VERIFICATION</span><h2>The seller verifies before serving.</h2><p className="demo-stage-copy">The seller checks the payment against its stored request: signature, payer, asset, minimum amount, expiry, and replay state. A passing <code>verify_payment</code> result unlocks the response.</p><div className="demo-verify"><span><Check size={23}/></span><div><strong>Payment verified</strong><p>0.01 SOL · expected buyer · fresh request</p></div><b>200 OK</b></div><div className="demo-serve">GET /report <ArrowRight size={17}/> Premium report delivered</div></>}
  {step===5&&<><span className="demo-eyebrow">/ OWNER DASHBOARD</span><h2>The balance and activity update.</h2><p className="demo-stage-copy">The owner sees decrypted amounts in Ringside’s dashboard. This example starts at 0.05 SOL and shows 0.04 SOL after the payment. The public chain does not reveal that balance.</p><div className="demo-dashboard"><div><span>PRIVATE BALANCE · DEMO DATA</span><strong>0.04 <small>SOL</small></strong><p>0.01 SOL paid to seller</p></div><div><span>LATEST ACTIVITY</span><article><div><b>{activity.type}</b><small>{activity.recipient}</small></div><strong>{activity.amount}</strong></article><em>{activity.status}</em></div></div></>}
  {step===6&&<><span className="demo-eyebrow">/ PUBLIC EXPLORER</span><h2>Here is what remains visible.</h2><p className="demo-stage-copy">The owner dashboard can decrypt the payment. A public observer sees the transfer and its addresses, but the default Ring’s amount and asset fields are encrypted.</p><div className="demo-explorer"><div><EyeOff size={18}/> EXPLORER VIEW · DEMO DATA</div><dl><dt>Transaction</dt><dd>5hT…9cA</dd><dt>Sender</dt><dd>7pN…2rD</dd><dt>Recipient</dt><dd>8kQ…3sV</dd><dt>Amount</dt><dd>••••</dd><dt>Asset</dt><dd>••••</dd></dl></div><p className="demo-stage-footnote">Deposits and withdrawals are public, including amount and asset. This masking describes a private transfer only.</p></>}
  </motion.div></AnimatePresence><div className="demo-stage-actions"><button className="demo-button secondary" onClick={reset}><RotateCcw size={16}/> Restart</button>{step<6?<button className="demo-button primary" onClick={next} disabled={checking||blocked||(step===0&&!valid)}>{step===0?'Save example limit':step===1?'Request payment':step===2?'Send private payment':step===3?'Verify payment':step===4?'View dashboard':'View explorer'} <ArrowRight size={16}/></button>:<Link className="demo-button primary" href="/docs">Explore the docs <ArrowRight size={16}/></Link>}</div></section></div><div className="demo-after"><div><span className="demo-eyebrow">/ TRY THE REAL PRODUCT</span><h2>Ready to connect an agent?</h2><p>Follow the setup guide for the self-hosted path. Live devnet transfers remain blocked in the latest Helius proof-service check.</p></div><Link className="demo-button primary" href="/docs">Read the setup guide <ArrowRight size={16}/></Link></div></main></div>;
}
