'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Check, EyeOff, LockKeyhole, RotateCcw, ShieldCheck } from 'lucide-react';
import { Brand } from '@/components/ringside/shell';
const amount = 0.01;
const steps = ['Set a limit', 'Agent requests payment', 'Policy check', 'Private transfer', 'Seller verifies', 'Dashboard updates', 'Explorer view'];
const activity = { type: 'Private payment', recipient: 'Data seller · 8kQ…3sV', amount: '−0.01 SOL', status: 'Verified' };
export default function DemoClient() {
  const [step,setStep]=useState(0),[limit,setLimit]=useState('0.05'),[checking,setChecking]=useState(false),[blocked,setBlocked]=useState(false);
  const reduced=useReducedMotion();
  const limitNumber=Number(limit); const valid=Number.isFinite(limitNumber)&&limitNumber>0;
  useEffect(()=>{if(step!==2||blocked)return;const timer=window.setTimeout(()=>{setChecking(false);setBlocked(!valid||limitNumber<amount)},reduced?0:1100);setChecking(true);return()=>window.clearTimeout(timer)},[step,valid,limitNumber,reduced,blocked]);
  const next=()=>{if(step===2&&(blocked||checking))return;setStep(current=>Math.min(current+1,6))};
  const reset=()=>{setStep(0);setBlocked(false);setChecking(false)};
  return <div className="demo-page"><header className="demo-header"><Brand/><nav><Link href="/">Home</Link><Link href="/docs">Docs</Link><Link className="demo-header-cta" href="/app">Open dashboard <ArrowRight size={15}/></Link></nav></header>
  <main className="demo-main"><div className="demo-hero"><Link href="/" className="demo-back"><ArrowLeft size={15}/> Back to Ringside</Link><span className="demo-eyebrow">/ NO INSTALL · GUIDED SCENARIO</span><h1>Watch an agent pay privately.</h1><p>Set a rule, follow a 0.01 SOL seller payment, and see what the owner and public explorer can each see.</p><div className="demo-data-banner"><span>DEMO DATA</span><p>This is a recorded, interactive scenario. No wallet connects, no funds move, and the figures below are examples. A live devnet private transfer is not yet verified because the Helius prover/indexer path failed in our latest checks.</p></div></div>
  <div className="demo-workspace"><aside className="demo-steps" aria-label="Demo steps">{steps.map((label,index)=><button type="button" key={label} className={index===step?'active':index<step?'done':''} onClick={()=>{if(index<=step){setStep(index);setBlocked(false)}}} disabled={index>step}><span>{index<step?<Check size={14}/>:String(index+1).padStart(2,'0')}</span>{label}</button>)}<div className="demo-steps-foot">Recorded scenario · Solana devnet target</div></aside>
  <section className="demo-stage" aria-live="polite"><div className="demo-stage-top"><span>STEP {String(step+1).padStart(2,'0')} / 07</span><span className="demo-data-tag">DEMO DATA</span></div><AnimatePresence mode="wait"><motion.div key={step} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={reduced?undefined:{opacity:0,y:-8}} transition={{duration:reduced?0:0.35}}>
  {step===0&&<><span className="demo-eyebrow">/ OWNER CONTROL</span><h2>First, give the agent a limit.</h2><p className="demo-stage-copy">The owner sets a maximum payment. In Ringside, a real policy change requires the owner wallet’s signature. Here you can adjust the example limit freely.</p><label className="demo-input-label" htmlFor="demo-limit">Maximum per payment · SOL</label><div className="demo-limit-input"><input id="demo-limit" type="number" inputMode="decimal" min="0.001" step="0.001" value={limit} onChange={event=>setLimit(event.target.value)}/><strong>SOL</strong></div><div className="demo-policy-card"><ShieldCheck size={20}/><div><strong>Owner policy preview</strong><span>Agent cannot change this rule. Payments above the limit are blocked before a transaction is built.</span></div></div></>}
  {step===1&&<><span className="demo-eyebrow">/ AGENT REQUEST</span><h2>The agent finds a paid answer.</h2><p className="demo-stage-copy">A seller asks for 0.01 SOL before serving its data. The agent receives a payment request with a destination, amount, asset, resource, nonce, and expiry.</p><div className="demo-quote"><span>HTTP 402 · PAYMENT REQUIRED</span><strong>Market report</strong><div><span>Requested payment</span><b>0.01 SOL</b></div><div><span>Seller</span><b>8kQ…3sV</b></div><div><span>Expires</span><b>In 5 minutes</b></div></div></>}
  {step===2&&<><span className="demo-eyebrow">/ POLICY ENGINE</span><h2>{checking?'Checking the owner’s rule…':blocked?'Payment stopped by policy.':'Payment fits the limit.'}</h2><p className="demo-stage-copy">Ringside checks the kill switch, allowed asset and recipient, and transaction, session, and day caps before spending.</p><div className="demo-check-list"><div className={checking?'working':'passed'}><span>{checking?'…':<Check size={17}/>}</span>Kill switch is off</div><div className={checking?'working':blocked?'failed':'passed'}><span>{checking?'…':blocked?'×':<Check size={17}/>}</span>0.01 SOL ≤ {valid?limit:'—'} SOL per-payment limit</div><div className={checking?'working':blocked?'idle':'passed'}><span>{checking?'…':blocked?'—':<Check size={17}/>}</span>Recipient is registered and permitted</div></div>{blocked&&<div className="demo-blocked">A 0.01 SOL payment exceeds this example limit. Go back, raise it to at least 0.01 SOL, and try again.</div>}</>}
  {step===3&&<><span className="demo-eyebrow">/ PRIVATE TRANSFER</span><h2>The payment is sent privately.</h2><p className="demo-stage-copy">In the recorded localnet run, Ringside synced encrypted notes, requested a proof, and submitted a private transfer. The default Ring hides the amount and asset on-chain; sender and recipient remain visible.</p><div className="demo-transfer"><div className="demo-transfer-node"><span>BUYER AGENT</span><strong>0.05 SOL</strong><small>Example private balance before</small></div><div className="demo-transfer-line"><LockKeyhole size={20}/><span>Encrypted amount + asset</span></div><div className="demo-transfer-node"><span>SELLER</span><strong>0.01 SOL</strong><small>Example payment received</small></div></div><p className="demo-stage-footnote">Illustrative values from a recorded scenario; this page does not submit a transaction.</p></>}
  {step===4&&<><span className="demo-eyebrow">/ SELLER VERIFICATION</span><h2>The seller verifies before serving.</h2><p className="demo-stage-copy">The seller checks the payment against its stored request: signature, payer, asset, minimum amount, expiry, and replay state. A passing <code>verify_payment</code> result unlocks the response.</p><div className="demo-verify"><span><Check size={23}/></span><div><strong>Payment verified</strong><p>0.01 SOL · expected buyer · fresh request</p></div><b>200 OK</b></div><div className="demo-serve">GET /report <ArrowRight size={17}/> Premium report delivered</div></>}
  {step===5&&<><span className="demo-eyebrow">/ OWNER DASHBOARD</span><h2>The balance and activity update.</h2><p className="demo-stage-copy">The owner sees decrypted amounts in Ringside’s dashboard. This example starts at 0.05 SOL and shows 0.04 SOL after the payment. The public chain does not reveal that balance.</p><div className="demo-dashboard"><div><span>PRIVATE BALANCE · DEMO DATA</span><strong>0.04 <small>SOL</small></strong><p>0.01 SOL paid to seller</p></div><div><span>LATEST ACTIVITY</span><article><div><b>{activity.type}</b><small>{activity.recipient}</small></div><strong>{activity.amount}</strong></article><em>{activity.status}</em></div></div></>}
  {step===6&&<><span className="demo-eyebrow">/ PUBLIC EXPLORER</span><h2>Here is what remains visible.</h2><p className="demo-stage-copy">The owner dashboard can decrypt the payment. A public observer sees the transfer and its addresses, but the default Ring’s amount and asset fields are encrypted.</p><div className="demo-explorer"><div><EyeOff size={18}/> EXPLORER VIEW · DEMO DATA</div><dl><dt>Transaction</dt><dd>5hT…9cA</dd><dt>Sender</dt><dd>7pN…2rD</dd><dt>Recipient</dt><dd>8kQ…3sV</dd><dt>Amount</dt><dd>••••</dd><dt>Asset</dt><dd>••••</dd></dl></div><p className="demo-stage-footnote">Deposits and withdrawals are public, including amount and asset. This masking describes a private transfer only.</p></>}
  </motion.div></AnimatePresence><div className="demo-stage-actions"><button className="demo-button secondary" onClick={reset}><RotateCcw size={16}/> Restart</button>{step<6?<button className="demo-button primary" onClick={next} disabled={checking||blocked||(step===0&&!valid)}>{step===0?'Save example limit':step===1?'Request payment':step===2?'Send private payment':step===3?'Verify payment':step===4?'View dashboard':'View explorer'} <ArrowRight size={16}/></button>:<Link className="demo-button primary" href="/docs">Explore the docs <ArrowRight size={16}/></Link>}</div></section></div><div className="demo-after"><div><span className="demo-eyebrow">/ TRY THE REAL PRODUCT</span><h2>Ready to connect an agent?</h2><p>Follow the setup guide for the self-hosted path. Live devnet transfers remain blocked in the latest Helius proof-service check.</p></div><Link className="demo-button primary" href="/docs">Read the setup guide <ArrowRight size={16}/></Link></div></main></div>;
}
