import 'server-only';
import { neon } from '@neondatabase/serverless';

export type OwnerRow={owner:string;agent_public:string;agent_cipher:string;policy:Record<string,unknown>};
let schemaReady:Promise<void>|undefined;
export function db(){const url=process.env.DATABASE_URL;if(!url)throw new Error('HOSTED_NOT_CONFIGURED: DATABASE_URL is required');return neon(url)}
export function ensureSchema(){return schemaReady??=migrate().catch(error=>{schemaReady=undefined;throw error})}
async function migrate(){const sql=db();await sql`CREATE TABLE IF NOT EXISTS hosted_owners (owner text PRIMARY KEY, agent_public text NOT NULL, agent_cipher text NOT NULL, policy jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS hosted_clients (client_id text PRIMARY KEY, name text NOT NULL, redirect_uris jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS hosted_authorizations (id text PRIMARY KEY, client_id text NOT NULL, redirect_uri text NOT NULL, state text NOT NULL, code_challenge text NOT NULL, expires_at timestamptz NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hosted_challenges (id text PRIMARY KEY, message text NOT NULL, flow_id text, expires_at timestamptz NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hosted_codes (hash text PRIMARY KEY, owner text NOT NULL, client_id text NOT NULL, redirect_uri text NOT NULL, code_challenge text NOT NULL, expires_at timestamptz NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hosted_tokens (hash text PRIMARY KEY, owner text NOT NULL, client_id text, kind text NOT NULL, expires_at timestamptz NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hosted_spends (id text PRIMARY KEY, owner text NOT NULL, asset text NOT NULL, amount_base numeric(40,0) NOT NULL, tool text NOT NULL, recipient text, signature text NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE INDEX IF NOT EXISTS hosted_spends_owner_time ON hosted_spends(owner,created_at)`}
export async function getOwner(owner:string){await ensureSchema();const rows=await db()`SELECT owner,agent_public,agent_cipher,policy FROM hosted_owners WHERE owner=${owner}`;return rows[0] as OwnerRow|undefined}
export async function getToken(tokenHash:string,kind:'access'|'refresh'|'session'){await ensureSchema();const rows=await db()`SELECT owner,client_id FROM hosted_tokens WHERE hash=${tokenHash} AND kind=${kind} AND expires_at>now()`;return rows[0] as {owner:string;client_id:string|null}|undefined}
