import 'server-only';
import { Pool } from 'pg';

export type OwnerRow={owner:string;agent_public:string;agent_cipher:string;registered:boolean;policy:Record<string,unknown>};
let schemaReady:Promise<void>|undefined;
let pool:Pool|undefined;
export function db(){const url=process.env.DATABASE_URL;if(!url)throw new Error('HOSTED_NOT_CONFIGURED: DATABASE_URL is required');pool??=new Pool({connectionString:url,max:5,connectionTimeoutMillis:5000,idleTimeoutMillis:30000});return async(strings:TemplateStringsArray,...values:unknown[])=>{let query=strings[0];for(let i=0;i<values.length;i++)query+=`$${i+1}`+strings[i+1];const result=await pool!.query(query,values);return result.rows}}
export function ensureSchema(){return schemaReady??=migrate().catch(error=>{schemaReady=undefined;throw error})}
async function migrate(){const sql=db();await sql`CREATE TABLE IF NOT EXISTS hosted_owners (owner text PRIMARY KEY, agent_public text NOT NULL, agent_cipher text NOT NULL, policy jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`;await sql`ALTER TABLE hosted_owners ADD COLUMN IF NOT EXISTS registered boolean NOT NULL DEFAULT false`;await sql`CREATE TABLE IF NOT EXISTS hosted_clients (client_id text PRIMARY KEY, name text NOT NULL, redirect_uris jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS hosted_authorizations (id text PRIMARY KEY, client_id text NOT NULL, redirect_uri text NOT NULL, state text NOT NULL, code_challenge text NOT NULL, expires_at timestamptz NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hosted_challenges (id text PRIMARY KEY, message text NOT NULL, flow_id text, expires_at timestamptz NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hosted_codes (hash text PRIMARY KEY, owner text NOT NULL, client_id text NOT NULL, redirect_uri text NOT NULL, code_challenge text NOT NULL, expires_at timestamptz NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hosted_tokens (hash text PRIMARY KEY, owner text NOT NULL, client_id text, kind text NOT NULL, expires_at timestamptz NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hosted_policy_nonces (nonce text PRIMARY KEY, owner text NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS hosted_payment_requests (owner text NOT NULL,nonce text PRIMARY KEY,body text NOT NULL,created_at bigint NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hosted_consumed_payments (signature text PRIMARY KEY,owner text NOT NULL,nonce text NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS hosted_spends (id text PRIMARY KEY, owner text NOT NULL, asset text NOT NULL, amount_base numeric(40,0) NOT NULL, tool text NOT NULL, recipient text, signature text NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS hosted_budgets (owner text NOT NULL, asset text NOT NULL, spent numeric(40,0) NOT NULL, window_started timestamptz NOT NULL, PRIMARY KEY(owner,asset))`;await sql`CREATE INDEX IF NOT EXISTS hosted_spends_owner_time ON hosted_spends(owner,created_at)`}
export async function getOwner(owner:string){await ensureSchema();const rows=await db()`SELECT owner,agent_public,agent_cipher,registered,policy FROM hosted_owners WHERE owner=${owner}`;return rows[0] as OwnerRow|undefined}
export async function getToken(tokenHash:string,kind:'access'|'refresh'|'session'){await ensureSchema();const rows=await db()`SELECT owner,client_id FROM hosted_tokens WHERE hash=${tokenHash} AND kind=${kind} AND expires_at>now()`;return rows[0] as {owner:string;client_id:string|null}|undefined}
