import 'server-only';
import { randomUUID } from 'node:crypto';
import { db,getOwner } from './db';
import { decryptAgent } from './crypto';
type HostedContext={owner:string;secretKey:Uint8Array;registered:boolean;markRegistered:()=>Promise<void>;savePaymentRequest:(nonce:string,body:string,createdAt:number)=>Promise<void>;getPaymentRequest:(nonce:string)=>Promise<{body:string;created_at:number}|undefined>;isPaymentConsumed:(signature:string)=>Promise<boolean>;consumePayment:(signature:string,nonce:string)=>Promise<boolean>;policy:{kill_switch:boolean;read_only:boolean;assets:Record<string,{max_per_tx:string;max_per_session:string;max_per_day:string}>;asset_allowlist:string[];recipient_allowlist:string[];allowlist_mode:'off'|'enforce';allow_withdrawal_fallback:boolean};budget:{asset:string;spent_today:string;spent_session:string;max_per_day:string;max_per_session:string};reserve:(tool:string,asset:string,amount:bigint,decimals:number,recipient?:string)=>Promise<void>;record:(tool:string,asset:string,amount:bigint,recipient:string|undefined,signature:string)=>Promise<void>};
import { runHosted } from 'ringside-mcp/hosted';

const units=(value:string,decimals:number)=>{if(!/^(0|[1-9]\d*)(\.\d+)?$/.test(value))throw new Error('Invalid policy amount');const [a,b='']=value.split('.');if(b.length>decimals)throw new Error('Invalid policy precision');return BigInt(a)*10n**BigInt(decimals)+BigInt(b.padEnd(decimals,'0')||'0')};
export async function withOwner<T>(owner:string,action:()=>Promise<T>){const row=await getOwner(owner);if(!row)throw new Error('HOSTED_OWNER_NOT_FOUND');const policy=row.policy as HostedContext['policy'];const secretKey=decryptAgent(owner,row.agent_cipher);const caps=policy.assets.SOL;const sql=db();const rows=await sql`SELECT spent,window_started FROM hosted_budgets WHERE owner=${owner} AND asset='SOL'`;const spent=rows[0]&&Date.now()-new Date(rows[0].window_started as string).getTime()<86400000?BigInt(String(rows[0].spent)):0n;const budget={asset:'SOL',spent_today:(Number(spent)/1e9).toString(),spent_session:(Number(spent)/1e9).toString(),max_per_day:caps?.max_per_day||'0',max_per_session:caps?.max_per_session||'0'};const context:HostedContext={owner,secretKey,registered:row.registered,markRegistered:async()=>{await db()`UPDATE hosted_owners SET registered=true WHERE owner=${owner}`},savePaymentRequest:async(nonce,body,createdAt)=>{await db()`INSERT INTO hosted_payment_requests(owner,nonce,body,created_at) VALUES(${owner},${nonce},${body},${createdAt})`},getPaymentRequest:async(nonce)=>{const rows=await db()`SELECT body,created_at FROM hosted_payment_requests WHERE owner=${owner} AND nonce=${nonce}`;return rows[0] as {body:string;created_at:number}|undefined},isPaymentConsumed:async(signature)=>{const rows=await db()`SELECT signature FROM hosted_consumed_payments WHERE signature=${signature}`;return !!rows[0]},consumePayment:async(signature,nonce)=>{const rows=await db()`INSERT INTO hosted_consumed_payments(signature,owner,nonce) VALUES(${signature},${owner},${nonce}) ON CONFLICT DO NOTHING RETURNING signature`;return !!rows[0]},policy,budget,
  reserve:async(tool,asset,amount,decimals,recipient)=>{const latest=await getOwner(owner);if(!latest)throw new Error('HOSTED_OWNER_NOT_FOUND');const current=latest.policy as HostedContext['policy'];if(current.kill_switch)throw new Error('KILL_SWITCH: owner has stopped spending');if(current.read_only)throw new Error('POLICY_DENIED: read-only mode');if(!current.asset_allowlist.includes(asset))throw new Error('POLICY_DENIED: asset is not allowed');if(current.allowlist_mode==='enforce'&&recipient&&!current.recipient_allowlist.includes(recipient))throw new Error('POLICY_DENIED: recipient is not allowed');const cap=current.assets[asset];if(!cap)throw new Error('POLICY_DENIED: no cap configured');if(amount>units(cap.max_per_tx,decimals))throw new Error('POLICY_DENIED: transaction cap exceeded');if(amount===0n)return;const daily=units(cap.max_per_day,decimals),session=units(cap.max_per_session,decimals);const max=daily<session?daily:session;const claim=await db()`INSERT INTO hosted_budgets(owner,asset,spent,window_started) VALUES(${owner},${asset},${amount.toString()},now()) ON CONFLICT(owner,asset) DO UPDATE SET spent=CASE WHEN hosted_budgets.window_started<now()-interval '24 hours' THEN EXCLUDED.spent ELSE hosted_budgets.spent+EXCLUDED.spent END,window_started=CASE WHEN hosted_budgets.window_started<now()-interval '24 hours' THEN now() ELSE hosted_budgets.window_started END WHERE CASE WHEN hosted_budgets.window_started<now()-interval '24 hours' THEN EXCLUDED.spent ELSE hosted_budgets.spent+EXCLUDED.spent END<=${max.toString()}::numeric RETURNING spent`;if(!claim[0])throw new Error('POLICY_DENIED: daily or session cap exceeded');void tool},
  record:async(tool,asset,amount,recipient,signature)=>{await db()`INSERT INTO hosted_spends(id,owner,asset,amount_base,tool,recipient,signature) VALUES(${randomUUID()},${owner},${asset},${amount.toString()},${tool},${recipient||null},${signature})`}};
 try{return await runHosted(context,action)}finally{secretKey.fill(0)}}
