import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Download } from 'lucide-react';
import { Brand } from '@/components/ringside/shell';
export const metadata: Metadata = { title: 'Brand · Ringside', description: 'Private payments for agents. Controls for owners. Download Ringside logos, colors, fonts, and title cards.' };
const assets=[['Light logo','/brand/logo-light.svg'],['Dark logo','/brand/logo-dark.svg'],['Light mark','/brand/mark-light.svg'],['Dark mark','/brand/mark-dark.svg']];
const colors=[['Ink','#0B0B0F'],['Paper','#F4F5F8'],['White','#FFFFFF'],['Periwinkle','#8B9BFF'],['Muted','#646A78']];
export default function BrandPage(){return <div className="brand-page"><header className="brand-page-header"><Brand/><nav><Link href="/">Home</Link><Link href="/docs">Docs</Link><Link href="/demo">Demo</Link></nav></header><main><span className="brand-page-eyebrow">/ RINGSIDE BRAND SYSTEM</span><h1>One mark. One promise.</h1><p className="brand-page-lede">Private payments for agents. Controls for owners.</p><div className="brand-page-intro"><p>The shield-shaped ring represents protected funds under owner control. Its lower gap stays open; the periwinkle stem is a deliberate signal, not a loading animation.</p><a className="brand-page-button" href="https://github.com/mayorXBT/Ringside-MCP/tree/main/brand" target="_blank" rel="noreferrer">Download the full brand kit <Download size={17}/></a></div>
<section><div className="brand-page-heading"><span>/ 01</span><h2>The mark</h2><p>Use the dark mark on light surfaces and the white mark on dark surfaces. Do not rotate, recolor, or close its gap.</p></div><div className="brand-page-logos"><div><img src="/brand/logo-light.svg" alt="Ringside dark wordmark and shield ring on a light background" width="360" height="80"/><a href="/brand/logo-light.svg" download>Download light logo <ArrowRight size={15}/></a></div><div className="dark"><img src="/brand/logo-dark.svg" alt="Ringside white wordmark and shield ring on a dark background" width="360" height="80"/><a href="/brand/logo-dark.svg" download>Download dark logo <ArrowRight size={15}/></a></div></div><div className="brand-page-asset-links">{assets.map(([name,url])=><a href={url} download key={name}>{name} <Download size={15}/></a>)}</div></section>
<section><div className="brand-page-heading"><span>/ 02</span><h2>Color and type</h2><p>Near-black text, cool off-white canvas, white cards, and restrained periwinkle. Headlines use Geist Sans Bold with tight tracking.</p></div><div className="brand-page-colors">{colors.map(([name,hex])=><div key={name}><i style={{background:hex}}/><strong>{name}</strong><span>{hex}</span></div>)}</div><div className="brand-page-type"><div><span>GEIST SANS · 700</span><strong>Private payments.</strong></div><div><span>GEIST SANS · 400</span><p>Clear tools. Clear controls. Clear privacy boundaries.</p></div></div><p className="brand-page-font-note">Geist font files and their license are included in the <a href="https://github.com/mayorXBT/Ringside-MCP/tree/main/brand/fonts">brand kit</a>.</p></section>
<section><div className="brand-page-heading"><span>/ 03</span><h2>Social and video</h2><p>Exported at publication sizes. Balance figures are illustrative demo data; the explorer view masks transfer amount and asset.</p></div><div className="brand-page-media"><article><img src="/opengraph-image.png" alt="Ringside Open Graph image with demo balance and masked explorer" width="1200" height="630"/><div><strong>Open Graph · 1200 × 630</strong><a href="/opengraph-image.png" download>Download PNG <Download size={15}/></a></div></article><article><img src="/brand/intro-1920x1080.png" alt="Ringside pitch video intro title card" width="1920" height="1080"/><div><strong>Pitch intro · 1920 × 1080</strong><a href="/brand/intro-1920x1080.png" download>Download PNG <Download size={15}/></a></div></article><article><img src="/brand/outro-1920x1080.png" alt="Ringside pitch video outro title card" width="1920" height="1080"/><div><strong>Pitch outro · 1920 × 1080</strong><a href="/brand/outro-1920x1080.png" download>Download PNG <Download size={15}/></a></div></article></div></section><footer><Brand/><p>Private payments for agents. Controls for owners.</p><Link href="/demo">Try the guided demo <ArrowRight size={16}/></Link></footer></main></div>}
