import { db,ensureSchema,getOwner } from '@/lib/hosted/db';
import { sessionOwner,problem } from '@/lib/hosted/http';
import { verifyOwnerAction } from '@/lib/hosted/signature';
import { withOwner } from '@/lib/hosted/service';
import { registerWallet,deposit,withdraw,walletInfo } from 'ringside-mcp/core';
import { z } from 'zod';
const policySchema=z.object({kill_switch:z.boolean(),read_only:z.boolean(),assets:z.object({SOL:z.object({max_per_tx:z.string().regex(/^(0|[1-9]\d*)(\.\d+)?$/),max_per_session:z.string().regex(/^(0|[1-9]\d*)(\.\d+)?$/),max_per_day:z.string().regex(/^(0|[1-9]\d*)(\.\d+)?$/)})}),asset_allowlist:z.array(z.string()),recipient_allowlist:z.array(z.string()),allowlist_mode:z.enum(['off','enforce']),allow_withdrawal_fallback:z.boolean()});
export const runtime='nodejs';
export const maxDuration=60;
export async function POST(request:Request){try{const owner=await sessionOwner();if(!owner)return problem(401,'login_required');const body=await request.json() as {action:string;payload:Record<string,unknown>;envelope:Record<string,string>;signature:string};if(!['register','deposit','withdraw','kill','policy'].includes(body.action)||!body.payload||!verifyOwnerAction(owner,body.action,body.payload,body.envelope,body.signature))return problem(403,'invalid_owner_signature');await ensureSchema();const nonce=await db()`INSERT INTO hosted_policy_nonces(nonce,owner) VALUES(${body.envelope.nonce},${owner}) ON CONFLICT DO NOTHING RETURNING nonce`;if(!nonce[0])return problem(409,'replayed_signature');if(body.action==='policy'){const policy=policySchema.parse(body.payload.policy);if(!policy.asset_allowlist.includes('SOL'))return problem(400,'sol_asset_required');await db()`UPDATE hosted_owners SET policy=${JSON.stringify(policy)}::jsonb WHERE owner=${owner}`;return Response.json({policy})}if(body.action==='kill'){const account=await getOwner(owner);if(!account)return problem(404,'owner_not_found');const on=body.payload.on===true;const policy={...account.policy,kill_switch:on};await db()`UPDATE hosted_owners SET policy=${JSON.stringify(policy)}::jsonb WHERE owner=${owner}`;return Response.json({policy})}const result=await withOwner(owner,async()=>{const info=await walletInfo();const publicLamports=BigInt(Math.round(Number(info.public_sol_balance)*1e9));const feeBuffer=5_000_000n;if(body.action==='register'&&publicLamports<feeBuffer)throw new Error('AGENT_NEEDS_FEE_SOL: Fund the agent public wallet with at least 0.01 devnet SOL, then retry registration.');if(body.action==='deposit'){const amount=Number(body.payload.amount);if(!Number.isFinite(amount)||amount<=0)throw new Error('INVALID_AMOUNT: Enter a positive SOL deposit amount.');if(publicLamports<BigInt(Math.round(amount*1e9))+feeBuffer)throw new Error('AGENT_NEEDS_FEE_SOL: The agent needs the deposit amount plus 0.005 SOL for network fees.');}if(body.action==='withdraw'&&publicLamports<feeBuffer)throw new Error('AGENT_NEEDS_FEE_SOL: The agent needs public SOL for the withdrawal network fee.');return body.action==='register'?registerWallet():body.action==='deposit'?deposit('SOL',String(body.payload.amount)):withdraw('SOL',String(body.payload.amount),body.payload.recipient?String(body.payload.recipient):undefined)});return Response.json(result,{headers:{'Cache-Control':'no-store'}})}catch(error){return problem(400,'action_failed',error instanceof Error?error.message:'Action failed')}}
