import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, BookOpen, ExternalLink, ShieldCheck } from 'lucide-react';
import { Brand } from '../../components/ringside/shell';
import { DocsCopy } from './ui';

export const metadata: Metadata = {
  title: 'Documentation · Ringside',
  description: 'Set up Ringside MCP, understand its owner controls and privacy model, and check what works on Solana devnet.',
};

const repo = 'https://github.com/mayorXBT/Ringside-MCP';
const groups = [
  { label: 'GET STARTED', links: [['Overview', 'overview'], ['Choose a mode', 'modes'], ['Self-host setup', 'self-host'], ['Connect an agent', 'connect']] },
  { label: 'USE RINGSIDE', links: [['First payment', 'first-payment'], ['Owner controls', 'controls'], ['MCP tools', 'tools'], ['Seller payments', 'seller']] },
  { label: 'REFERENCE', links: [['Privacy model', 'privacy'], ['Availability', 'availability'], ['Troubleshooting', 'troubleshooting']] },
] as const;
const install = `git clone --recurse-submodules https://github.com/mayorXBT/Ringside-MCP.git\ncd Ringside-MCP\npnpm install --frozen-lockfile\npnpm build`;
const initialize = `export HELIUS_API_KEY='your-devnet-key'\nnode packages/mcp/dist/index.js init --owner YOUR_OWNER_WALLET_ADDRESS`;
const config = `{
  "mcpServers": {
    "ringside": {
      "command": "node",
      "args": ["--use-env-proxy", "/absolute/path/Ringside-MCP/packages/mcp/dist/index.js"],
      "env": {
        "HELIUS_API_KEY": "your-devnet-key",
        "RINGSIDE_KEYPAIR": "/absolute/path/agent.json"
      }
    }
  }
}`;
function Code({ children, label }: { children: string; label: string }) { return <div className="docs-code"><div className="docs-code-head"><span>{label}</span><DocsCopy text={children}/></div><pre><code>{children}</code></pre></div>; }
function Note({ children, tone = 'default' }: { children: React.ReactNode; tone?: 'default' | 'warning' }) { return <aside className={`docs-note ${tone}`}><ShieldCheck size={19} aria-hidden="true"/><div>{children}</div></aside>; }
function Section({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: React.ReactNode }) { return <section id={id} className="docs-section"><span className="docs-eyebrow">/ {eyebrow}</span><h2>{title}</h2>{children}</section>; }
export default function DocsPage() { return <div className="docs-page">
  <header className="docs-top"><Brand/><span className="docs-top-divider"/><span className="docs-top-title">Documentation</span><nav aria-label="Documentation header"><Link href="/onboard">Connect an agent</Link><a href={repo} target="_blank" rel="noreferrer">GitHub <ExternalLink size={14}/></a><Link className="docs-dashboard" href="/app">Open dashboard <ArrowRight size={15}/></Link></nav></header>
  <div className="docs-mobile-nav"><details><summary><BookOpen size={18}/> Browse documentation</summary><div>{groups.map(group=><div key={group.label}><strong>{group.label}</strong>{group.links.map(([name,id])=><a href={`#${id}`} key={id}>{name}</a>)}</div>)}</div></details></div>
  <div className="docs-layout"><aside className="docs-sidebar" aria-label="Documentation navigation"><div className="docs-sidebar-inner"><div className="docs-sidebar-intro">RINGSIDE DOCS <span>Devnet beta</span></div>{groups.map(group=><nav aria-label={group.label} key={group.label}><h2>{group.label}</h2>{group.links.map(([name,id])=><a href={`#${id}`} key={id}>{name}</a>)}</nav>)}<div className="docs-sidebar-bottom"><a href={`${repo}/blob/main/STATUS.md`} target="_blank" rel="noreferrer">Build status ↗</a><a href={`${repo}/blob/main/scripts/demo.md`} target="_blank" rel="noreferrer">Demo runbook ↗</a></div></div></aside>
  <main className="docs-content"><div className="docs-content-inner"><div className="docs-breadcrumb">Documentation <span>/</span> Start here</div><div className="docs-hero" id="overview"><span className="docs-eyebrow">/ THE GUIDE</span><h1>Private payments.<br/>Clear controls.</h1><p>Ringside gives MCP agents a payment wallet on Solana Rings, with owner-defined spending rules and a seller verification flow. This guide covers setup, daily use, and the limits of the current devnet release.</p><div className="docs-hero-actions"><a className="docs-button dark" href="#self-host">Start building <ArrowRight size={17}/></a><Link className="docs-button pale" href="/onboard">Connector guide <ArrowRight size={17}/></Link></div></div>
  <Note tone="warning"><strong>Current release:</strong> Self-hosted flows passed on Zolana localnet. Hosted signup is waiting for production Postgres, and Helius devnet proof services currently prevent a verified live private transfer. Use test funds only. <a href="#availability">See the availability table.</a></Note>
  <Section id="modes" eyebrow="BEFORE YOU START" title="Choose how to run Ringside"><p>The two modes share the MCP tool surface. They differ in where the agent key is held and how you connect.</p><div className="docs-mode-grid"><article><span>01 / HOSTED</span><h3>Paste one connector URL</h3><p>Claude or ChatGPT connects to <code>https://ringside-dashboard.vercel.app/mcp</code>. You sign in with your Solana wallet; Ringside creates an agent key encrypted on the server. The dashboard uses the same owner session.</p><strong className="docs-state pending">Signup pending production storage</strong><Link href="/onboard">View connector steps <ArrowRight size={15}/></Link></article><article><span>02 / SELF-HOST</span><h3>Keep the key on your machine</h3><p>Run the stdio MCP server alongside your agent. Its keypair and policy live locally; your owner wallet signs changes. This is the currently usable path for localnet development.</p><strong className="docs-state">Available to build from source</strong><a href="#self-host">Set up self-hosting <ArrowRight size={15}/></a></article></div></Section>
  <Section id="self-host" eyebrow="INSTALLATION" title="Set up a local agent"><p>Use Node 24 or newer and pnpm 11. Clone the repository with its upstream submodules, then build the packages.</p><Code label="Terminal · install" >{install}</Code><p>Set a Helius devnet API key and initialize a dedicated agent wallet. <code>init</code> prints the public funding address. Keep the key file out of Git and give it mode <code>600</code>.</p><Code label="Terminal · initialize">{initialize}</Code><Note>The owner wallet signs policy changes; it does not need to be the agent fee payer. Fund the agent address with devnet SOL for network fees and deposits. For an existing key, see the <a href={`${repo}/blob/main/README.md#self-host-advanced`} target="_blank" rel="noreferrer">README</a>.</Note></Section>
  <Section id="connect" eyebrow="MCP CLIENTS" title="Connect your agent"><p>Add the stdio server to Claude Desktop with absolute paths. Replace the API key and key file path with your own values. The same command and environment work in Claude Code and Cursor.</p><Code label="Claude Desktop · MCP configuration">{config}</Code><p>Restart your MCP client after saving its configuration. Ask it for <code>wallet_info</code>, then <code>register_private_wallet</code>. Registration is required before private transfers. The server has 25 registered tools; spending tools are marked destructive so clients can request confirmation.</p><div className="docs-inline-links"><Link href="/onboard">Hosted connector instructions <ArrowRight size={16}/></Link><a href={`${repo}/blob/main/scripts/demo.md`} target="_blank" rel="noreferrer">Localnet demo runbook <ExternalLink size={15}/></a></div></Section>
  <Section id="first-payment" eyebrow="FIRST TRANSACTION" title="From funding to payment"><ol className="docs-steps"><li><span>01</span><div><h3>Register and fund</h3><p>Register the agent wallet, send devnet SOL to its public address, then call <code>deposit</code> to move funds into its private balance. The funding and deposit amounts remain public on-chain.</p></div></li><li><span>02</span><div><h3>Sync the private balance</h3><p>Call <code>get_private_balance</code> to see the decrypted balance available to this agent. The agent reads its own private notes locally or in the hosted request context.</p></div></li><li><span>03</span><div><h3>Pay a registered recipient</h3><p>Call <code>private_transfer</code> with the recipient, asset, and amount. Ringside checks the kill switch, recipient registration, allowlist, and spend caps before submission.</p></div></li><li><span>04</span><div><h3>Read or withdraw</h3><p>Use <code>get_private_history</code> for activity, or <code>withdraw</code> to return funds to a public wallet. Withdrawal details are public.</p></div></li></ol><Note tone="warning">The complete SOL transfer and withdrawal loop passed on Zolana localnet. Helius devnet registration and deposits passed, but its prover/indexer blocked the live transfer proof. The guarded retry is <code>RINGSIDE_RUN_LIVE_TRANSFER=1 pnpm check:live-transfer</code>.</Note></Section>
  <Section id="controls" eyebrow="OWNER POLICY" title="Rules run before funds move"><p>Ringside enforces per-transaction, session, and rolling 24-hour caps. Owners can restrict recipients, make an agent read-only, or stop all spending with a kill switch. The agent has <code>get_policy</code> for inspection, but no tool to change its own policy.</p><div className="docs-fact-grid"><div><strong>0.05 SOL</strong><span>Hosted default per transaction</span></div><div><strong>0.2 SOL</strong><span>Hosted default per 24 hours</span></div><div><strong>60 seconds</strong><span>Owner signature validity</span></div></div><p>The owner dashboard requires a wallet signature for policy changes. Self-hosted policy and pairing data remain on the agent machine. Hosted mode stores the agent key encrypted at rest and enforces a durable spend reservation before sending a transaction. These defaults are for devnet test funds, not a guarantee against loss.</p><Link className="docs-text-link" href="/app">Open owner dashboard <ArrowRight size={17}/></Link></Section>
  <Section id="tools" eyebrow="TOOL REFERENCE" title="One MCP surface, 25 tools"><p>Names below are the names your MCP client discovers. Aliases are listed so prompts can use either wording.</p><div className="docs-tool-groups"><div><h3>Wallet and balances <span>8</span></h3><p><code>wallet_info</code>, <code>register_private_wallet</code>, <code>create_private_wallet</code>, <code>deposit</code>, <code>sync_balance</code>, <code>get_private_balance</code>, <code>read_history</code>, <code>get_private_history</code></p></div><div><h3>Payments and policy <span>8</span></h3><p><code>private_transfer</code>, <code>withdraw</code>, <code>deposit_with_interface_setup</code>, <code>create_test_token</code>, <code>get_policy</code>, <code>create_payment_request</code>, <code>pay_payment_request</code>, <code>verify_payment</code></p></div><div><h3>Swap and escrow preview <span>9</span></h3><p><code>swap_make_order</code>, <code>swap_list_orders</code>, <code>swap_take_order</code>, <code>swap_take_order_verifiable</code>, <code>swap_cancel_order</code>, <code>escrow_lock</code>, <code>escrow_list</code>, <code>escrow_withdraw</code>, <code>escrow_release</code></p><small>Tier C: discoverable, but currently return ENGINE_UNAVAILABLE. Do not lock funds with this release.</small></div></div></Section>
  <Section id="seller" eyebrow="SELLER FLOW" title="Request. Pay. Verify. Serve."><p>A seller can request payment for a resource, the buyer agent can pay privately, and the seller can verify the resulting receipt before returning data. The demo API responds with HTTP 402 until verification passes; replayed receipts are rejected.</p><div className="docs-flow"><div><span>01 / REQUEST</span><strong>402</strong><small>Seller creates a time-limited payment request.</small></div><b aria-hidden="true">→</b><div><span>02 / PAYMENT</span><strong>Private</strong><small>Agent pays and returns a payment proof.</small></div><b aria-hidden="true">→</b><div><span>03 / VERIFY</span><strong>200</strong><small>Seller checks payment before serving data.</small></div></div><p>The SOL seller flow passed on localnet. The request nonce is held by the verifier and has a short expiry; it is not yet bound to an on-chain memo. The verifier also rejects payments older than the request.</p><a className="docs-text-link" href={`${repo}/blob/main/scripts/demo.md`} target="_blank" rel="noreferrer">Run the seller demo <ExternalLink size={16}/></a></Section>
  <Section id="privacy" eyebrow="PRIVACY MODEL" title="Know what the chain reveals"><p>“Private” describes the payment fields hidden by the default ring transfer. It does not make every part of a transaction invisible.</p><div className="docs-table-wrap"><table><thead><tr><th>Action</th><th>Hidden on-chain</th><th>Public on-chain</th></tr></thead><tbody><tr><td>Private transfer</td><td>Amount, asset</td><td>Sender, recipient, signature, timing</td></tr><tr><td>Deposit</td><td>—</td><td>Wallet, amount, asset</td></tr><tr><td>Withdrawal</td><td>—</td><td>Recipient, amount, asset</td></tr><tr><td>Seller payment</td><td>Amount, asset</td><td>Payer, seller, signature</td></tr></tbody></table></div><p><strong>Funding is public; payments are private.</strong> A public observer may infer relationships from timing and visible addresses. In self-hosted mode the agent key remains local. In hosted mode Ringside holds an encrypted agent key and can access it to execute authorized requests.</p><a className="docs-text-link" href={`${repo}/blob/main/docs/security.md`} target="_blank" rel="noreferrer">Read the security model <ExternalLink size={16}/></a></Section>
  <Section id="availability" eyebrow="RELEASE STATUS" title="What works today"><div className="docs-table-wrap"><table><thead><tr><th>Capability</th><th>Current result</th></tr></thead><tbody><tr><td>Core SOL payment and withdrawal</td><td>Passed end to end on Zolana localnet.</td></tr><tr><td>Devnet registration and deposit</td><td>Passed; private transfer blocked by Helius prover/indexer.</td></tr><tr><td>Hosted OAuth and MCP</td><td>Local PostgreSQL test passed registration, PKCE, signed login, 25 tools, and policy denial. Production signup awaits Postgres.</td></tr><tr><td>Swap and escrow</td><td>Tier C. Tools are listed, but engine actions are unavailable.</td></tr><tr><td>Claude / ChatGPT hosted connector</td><td>Real account login and payment remain unverified.</td></tr></tbody></table></div><p>This table reflects the Oct 10, 2026 build. <a href={`${repo}/blob/main/STATUS.md`} target="_blank" rel="noreferrer">STATUS.md</a> is the detailed, updated record of checks, blockers, and next steps.</p></Section>
  <Section id="troubleshooting" eyebrow="SUPPORT" title="When something stops"><div className="docs-troubles"><details><summary>The MCP client cannot start Ringside</summary><p>Confirm Node 24+, run <code>pnpm build</code>, and use absolute paths in the client configuration. Check that the key file exists, has mode 600, and stays outside the repository.</p></details><details><summary>Registration or transfer fails on devnet</summary><p>Confirm <code>HELIUS_API_KEY</code> is set for devnet. The current Helius prover/indexer failure affects transfer proof generation; use the localnet runbook while that upstream path is unavailable.</p></details><details><summary>The dashboard cannot find my self-hosted agent</summary><p>Run the local control API on the agent machine, generate a pairing token, and select Self-host (advanced). Keep <code>RINGSIDE_HOME</code> consistent across the MCP process and dashboard control API.</p></details><details><summary>Hosted login says setup is pending</summary><p>Production Postgres is not connected yet. Hosted wallet creation is intentionally disabled until durable encrypted storage is available. Self-hosting remains the working setup path.</p></details></div></Section>
  <footer className="docs-footer"><div><Brand/><p>Private agent payments on Solana devnet.</p></div><div><a href={`${repo}/blob/main/PRD.md`} target="_blank" rel="noreferrer">Product requirements</a><a href={`${repo}/blob/main/STATUS.md`} target="_blank" rel="noreferrer">Build status</a><a href={`${repo}/blob/main/README.md`} target="_blank" rel="noreferrer">README</a></div></footer>
  </div></main><aside className="docs-toc" aria-label="On this page"><div><strong>ON THIS PAGE</strong>{[['Choose a mode','modes'],['Self-host setup','self-host'],['Connect an agent','connect'],['First payment','first-payment'],['Owner controls','controls'],['MCP tools','tools'],['Seller payments','seller'],['Privacy model','privacy'],['Availability','availability']].map(([name,id])=><a href={`#${id}`} key={id}>{name}</a>)}</div></aside></div>
</div>; }
